import type {Family,FamilyMembership,Household,Person,ResidencePeriod} from "@/src/contracts/family";
import type {ExternalLink,ExternalResource,InterpersonalRelationship,RelationshipQuality} from "@/src/contracts/relations";
import {lifeStageSubtitle,resourceSubtitle} from "./diagram-labels";
export interface DiagramNode{id:string;label:string;subtitle?:string;kind:"person"|"family"|"resource"|"household";x:number;y:number;state?:string;}
export interface DiagramEdge{id:string;sourceId:string;targetId:string;label:string;quality:RelationshipQuality;direction:"mutual"|"from-source"|"to-source"|"none";perspective:string;}
export interface DiagramModel{kind:"genogram"|"ecomap";nodes:DiagramNode[];edges:DiagramEdge[];perspectiveLabel:string;periodLabel:string;manifest:{expectedNodes:number;expectedEdges:number;divergentEdges:number;};}
const ring=(index:number,total:number,radius:number,centerX=300,centerY=220)=>{const angle=-Math.PI/2+(index*Math.PI*2)/Math.max(total,1);return{x:centerX+Math.cos(angle)*radius,y:centerY+Math.sin(angle)*radius}};
export function buildGenogram(input:{family:Family;people:Person[];memberships:FamilyMembership[];relationships:InterpersonalRelationship[];households?:Household[];residences?:ResidencePeriod[];layer:"structural"|"household"|"clinical"|"functional";perspectivePersonId?:string;periodLabel?:string}):DiagramModel{const members=input.memberships.filter((m)=>m.familyId===input.family.id&&!m.validTo);const people=input.people.filter((p)=>members.some((m)=>m.personId===p.id));const nodes:DiagramNode[]=people.map((p,i)=>{const pos=ring(i,people.length,145);const role=members.find((m)=>m.personId===p.id)?.roleLabel;const subtitle=input.layer==="functional"?role:input.layer==="household"?"domicílio a revisar":p.lifeStage;return{id:p.id,label:p.displayName||p.code,...(subtitle?{subtitle}:{}),kind:"person",...pos}});const visible=input.relationships.filter((r)=>r.familyId===input.family.id&&!r.validTo&&(!input.perspectivePersonId||!r.perspectivePersonId||r.perspectivePersonId===input.perspectivePersonId));const edges=visible.map((r)=>({id:r.id,sourceId:r.sourcePersonId,targetId:r.targetPersonId,label:r.formalType,quality:r.quality,direction:r.direction,perspective:r.perspectiveLabel}));return{kind:"genogram",nodes,edges,perspectiveLabel:input.perspectivePersonId?people.find((p)=>p.id===input.perspectivePersonId)?.displayName||"Perspectiva selecionada":"Consolidada",periodLabel:input.periodLabel||"Atual",manifest:{expectedNodes:nodes.length,expectedEdges:edges.length,divergentEdges:edges.filter((e)=>e.quality==="divergent").length}}}
export function buildEcomap(input:{family:Family;people:Person[];resources:ExternalResource[];links:ExternalLink[];perspectivePersonId?:string;periodLabel?:string}):DiagramModel{const center:DiagramNode={id:input.family.id,label:input.family.nickname||input.family.code,subtitle:"família",kind:"family",x:300,y:220};const resources=input.resources.filter((r)=>r.familyId===input.family.id&&r.state!=="closed");const linkedPeople=input.people.filter((person)=>input.links.some((link)=>link.familyId===input.family.id&&link.personId===person.id));const personNodes=linkedPeople.map((person,index)=>({id:person.id,label:person.displayName||person.code,subtitle:"membro",kind:"person" as const,...ring(index,Math.max(linkedPeople.length,1),72)}));const nodes=[center,...personNodes,...resources.map((r,i)=>({id:r.id,label:r.name,subtitle:resourceSubtitle(r),kind:"resource" as const,...ring(i,resources.length,175)}))];const visible=input.links.filter((l)=>l.familyId===input.family.id&&!l.validTo&&(!input.perspectivePersonId||!l.perspectivePersonId||l.perspectivePersonId===input.perspectivePersonId));const edges=visible.map((l)=>({id:l.id,sourceId:l.personId||input.family.id,targetId:l.resourceId,label:l.intensity,quality:l.quality,direction:l.direction,perspective:l.perspectiveLabel}));return{kind:"ecomap",nodes,edges,perspectiveLabel:input.perspectivePersonId?input.people.find((p)=>p.id===input.perspectivePersonId)?.displayName||"Perspectiva selecionada":"Consolidada",periodLabel:input.periodLabel||"Atual",manifest:{expectedNodes:nodes.length,expectedEdges:edges.length,divergentEdges:edges.filter((e)=>e.quality==="divergent").length}}}
export function relationshipNarrative(model:DiagramModel):string{const nodes=new Map(model.nodes.map((n)=>[n.id,n.label]));const lines=model.edges.map((e)=>`${nodes.get(e.sourceId)||"Família"} → ${nodes.get(e.targetId)||"recurso"}: ${e.label}, vínculo ${e.quality}, direção ${e.direction}, perspectiva ${e.perspective}.`);return[`Mapa ${model.kind==="genogram"?"familiar":"de rede"}.`,`Perspectiva: ${model.perspectiveLabel}. Período: ${model.periodLabel}.`,`${model.manifest.expectedNodes} entidades e ${model.manifest.expectedEdges} vínculos.`,...lines].join("\n")}
export function qualityStyle(q:RelationshipQuality){return q==="strong"?{stroke:"#0f766e",width:5,dash:""}:q==="conflict"?{stroke:"#b45309",width:3,dash:"3 4"}:q==="weak"?{stroke:"#64748b",width:2,dash:"7 6"}:q==="ruptured"?{stroke:"#991b1b",width:3,dash:"2 8"}:q==="divergent"?{stroke:"#7e22ce",width:4,dash:"9 4 2 4"}:{stroke:"#475569",width:2,dash:""}}
