import type { PharmacologyEntry } from "./types";

/**
 * CATÁLOGO FARMACOLÓGICO AUTORAL
 *
 * Arquivo compilado com todas as classes e fármacos discutidos:
 * Biguanidas, Inibidores de SGLT2, Moduladores do SRAA (IECAs e BRAs),
 * Inibidores da HMG-CoA Redutase (Estatinas), Diuréticos, Bloqueadores dos Canais de Cálcio
 * e Analgésicos / Anti-inflamatórios Não Esteroidais.
 */
export const pharmacologyCatalog: PharmacologyEntry[] = [
  // ==========================================
  // 1. BIGUANIDAS
  // ==========================================
  {
    id: "metformina",
    genericName: "Cloridrato de Metformina",
    brandNames: ["Glifage", "Glifage XR", "Dimefor", "Glucophage"],
    therapeuticClass: "Antidiabético Oral / Biguanida",
    mechanism:
      "Ativação da AMPK (AMP-activated protein kinase) hepática, inibição da gliconeogênese mitocondrial dependente de glicerol-3-fosfato desidrogenase e aumento da sensibilidade periférica à insulina.",
    presentations: [
      "Comprimidos de liberação imediata (IR): 500 mg, 850 mg, 1000 mg",
      "Comprimidos de liberação prolongada (XR): 500 mg, 750 mg, 1000 mg",
    ],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Diabetes Mellitus Tipo 2 (Liberação Imediata - IR)",
        route: "Via Oral",
        presentation: "Comprimidos IR (500 mg, 850 mg, 1000 mg)",
        initial: "500 mg a cada 12h ou 850 mg 1x/dia, administrados junto às refeições",
        titration: "Incrementos de 500 mg a cada 1 a 2 semanas conforme tolerabilidade gastrointestinal e glicemia de jejum",
        usual: "1500 mg a 2000 mg/dia divididos em 2 ou 3 tomadas",
        interval: "A cada 8 horas ou 12 horas",
        target: "2000 mg/dia fracionados",
        maximum: "2550 mg/dia (3 tomadas de 850 mg)",
        duration: "Contínua / Longo prazo",
        renalAdjustment:
          "TFG 45-59 mL/min: dose máxima de 2000 mg/dia. TFG 30-44 mL/min: não iniciar; se em uso, reduzir dose em 50% (máx 1000 mg/dia). TFG < 30 mL/min: contraindicado.",
        hepaticAdjustment: "Evitar o uso em insuficiência hepática avançada pelo risco de comprometimento do clearance de lactato.",
        notes: "Administração junto às refeições reduz sintomas dispépticos e diarreia osmótica.",
      },
      {
        population: "Adultos",
        indication: "Diabetes Mellitus Tipo 2 (Liberação Prolongada - XR)",
        route: "Via Oral",
        presentation: "Comprimidos XR (500 mg, 750 mg, 1000 mg)",
        initial: "500 mg a 1000 mg, 1x/dia, durante o jantar",
        titration: "Aumentar em 500 mg semanalmente conforme glicemia e tolerância",
        usual: "1500 mg a 2000 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "2000 mg, 1x/dia no jantar",
        maximum: "2000 mg/dia",
        duration: "Contínua / Longo prazo",
        renalAdjustment: "Mesmos pontos de corte da forma IR; teto de 1000 mg/dia se TFG entre 30-44 mL/min.",
        hepaticAdjustment: "Contraindicado em hepatopatia descompensada.",
        notes: "Comprimidos de liberação prolongada não devem ser partidos ou mastigados.",
      },
    ],
    contraindications: [
      "TFG < 30 mL/min/1,73m²",
      "Acidose metabólica aguda ou crônica (incluindo cetoacidose diabética)",
      "Quadros de hipóxia tecidual aguda (choque séptico, cardiogênico, IAM recente, insuficiência respiratória grave)",
      "Insuficiência hepática grave",
    ],
    warnings: [
      "Risco de acidose láctica associada à metformina (MALA), rara porém com alta mortalidade",
      "Deficiência de vitamina B12 associada ao uso crônico por má absorção ileal",
      "Suspender 48h antes de exames com contraste iodado intravascular se TFG < 60 mL/min ou instabilidade clínica",
    ],
    interactions: [
      "Contrastes iodados (risco de nefropatia induzida por contraste e acúmulo da droga)",
      "Álcool (potencializa o acúmulo de lactato por inibição da gliconeogênese hepática)",
      "Cimetidina e outros inibidores de transportadores OCT2/MATE (aumentam os níveis séricos de metformina)",
    ],
    monitoring: [
      "Taxa de Filtração Glomerular e creatinina sérica basal e a cada 3-6 meses em grupos de risco",
      "Hemoglobina Glicada (HbA1c) a cada 3 meses até a meta, depois semestral",
      "Dosagem sérica de Vitamina B12 anualmente em tratamentos prolongados (> 3-5 anos)",
    ],
    sources: [
      { title: "Standards of Care in Diabetes", organization: "American Diabetes Association (ADA)" },
      { title: "Diretrizes da Sociedade Brasileira de Diabetes", organization: "SBD" },
    ],
    reviewStatus: "reviewed",
    notes: "Fármaco de primeira linha no DM2, sem ganho ponderal e com risco intrínseco quase nulo de hipoglicemia em monoterapia.",
  },

  // ==========================================
  // 2. INIBIDORES DE SGLT2 (ANTIDIABÉTICOS CARDIORRENAIS)
  // ==========================================
  {
    id: "dapagliflozina",
    genericName: "Dapagliflozina",
    brandNames: ["Forxiga"],
    therapeuticClass: "Inibidor do Cotransportador Sódio-Glicose 2 (iSGLT2)",
    mechanism:
      "Inibição seletiva do transportador SGLT2 no túbulo contorcido proximal renal, promovendo glicosúria, natriurese osmótica, restauração do feedback tubuloglomerular e vasoconstrição da arteríola aferente.",
    presentations: ["Comprimidos revestidos de 5 mg e 10 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Insuficiência Cardíaca (ICFEr/ICFEl/ICFEp) e Doença Renal Crônica (DRC)",
        route: "Via Oral",
        presentation: "Comprimido 10 mg",
        initial: "10 mg, 1x/dia, pela manhã",
        titration: "Dose fixa; não necessita de escalonamento",
        usual: "10 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "10 mg, 1x/dia",
        maximum: "10 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Pode ser iniciada se TFG ≥ 20 ou 25 mL/min/1,73m² e mantida até início de diálise/transplante.",
        hepaticAdjustment: "Não requer ajuste em insuficiência leve a moderada. Avaliar risco-benefício em Child-Pugh C.",
        notes: "O benefício cardiorrenal independe da presença de Diabetes Mellitus.",
      },
      {
        population: "Adultos",
        indication: "Diabetes Mellitus Tipo 2",
        route: "Via Oral",
        presentation: "Comprimidos 5 mg e 10 mg",
        initial: "5 mg a 10 mg, 1x/dia",
        titration: "Pode titular de 5 mg para 10 mg após 2-4 semanas se objetivo glicêmico exigir",
        usual: "10 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "10 mg, 1x/dia",
        maximum: "10 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Perde eficácia redutora de glicose com TFG < 45 mL/min, mas os benefícios cardiovasculares persistem.",
        hepaticAdjustment: "Sem ajuste para insuficiência leve/moderada.",
        notes: "Reduz pressão arterial sistólica em 2 a 4 mmHg e peso corporal em 2 a 3 kg.",
      },
    ],
    contraindications: ["Hipersensibilidade à droga", "Pacientes em hemodiálise ou diálise peritoneal"],
    warnings: [
      "Risco de cetoacidose diabética euglicêmica (suspender temporariamente antes de cirurgias de grande porte)",
      "Infecções micóticas genitais recorrentes (candidíase vulvovaginal e balanite)",
      "Queda funcional inicial reversível da TFG de até 20-30% nas primeiras semanas de tratamento",
      "Fasciíte necrosante do períneo (Gangrena de Fournier), rara porém grave",
    ],
    interactions: [
      "Diuréticos de alça e tiazídicos (risco potencializado de depleção volêmica e hipotensão ortostática)",
      "Insulina e sulfonilureias (aumento do risco de hipoglicemia; considerar redução profilática da dose destes)",
    ],
    monitoring: [
      "Função renal e eletrólitos basais e após 2 a 4 semanas do início",
      "Sinais flogísticos em região perineal e genital",
      "Sintomas de depleção de volume (tontura, hipotensão postural)",
    ],
    sources: [
      { title: "DAPA-HF / DAPA-CKD Trials", organization: "New England Journal of Medicine (NEJM)" },
      { title: "Diretrizes de Insuficiência Cardíaca", organization: "Sociedade Brasileira de Cardiologia (SBC)" },
    ],
    reviewStatus: "reviewed",
    notes: "Um dos 4 pilares farmacológicos com redução comprovada de mortalidade na ICFEr.",
  },
  {
    id: "empagliflozina",
    genericName: "Empagliflozina",
    brandNames: ["Jardiance"],
    therapeuticClass: "Inibidor do Cotransportador Sódio-Glicose 2 (iSGLT2)",
    mechanism:
      "Inibição potente e competitiva do transportador SGLT2 na borda em escova do túbulo proximal, com excreção urinária de glicose e sódio, aliviando hiperfiltração glomerular e sobrecarga cardíaca.",
    presentations: ["Comprimidos revestidos de 10 mg e 25 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Insuficiência Cardíaca (ICFEr / ICFEp) e Doença Renal Crônica",
        route: "Via Oral",
        presentation: "Comprimido 10 mg",
        initial: "10 mg, 1x/dia, pela manhã",
        titration: "Sem necessidade de escalonamento",
        usual: "10 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "10 mg, 1x/dia",
        maximum: "10 mg/dia para indicações cardiorrenais",
        duration: "Contínua",
        renalAdjustment: "Pode ser iniciada em pacientes com TFG ≥ 20 mL/min/1,73m².",
        hepaticAdjustment: "Sem ajuste específico necessário.",
        notes: "A dose de 25 mg não demonstrou benefício incremental de mortalidade sobre a de 10 mg em ensaios de IC.",
      },
      {
        population: "Adultos",
        indication: "Diabetes Mellitus Tipo 2",
        route: "Via Oral",
        presentation: "Comprimidos 10 mg e 25 mg",
        initial: "10 mg, 1x/dia",
        titration: "Pode ser elevada para 25 mg após 4 semanas para intensificação do controle glicêmico",
        usual: "10 mg a 25 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "25 mg, 1x/dia se tolerada e indicada para HbA1c",
        maximum: "25 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Glicosúria dependente de TFG; suspender como hipoglicemiante se TFG persistentemente < 30.",
        hepaticAdjustment: "Não recomendado em insuficiência hepática fulminante.",
        notes: "Demonstrou pioneiramente redução significativa de mortalidade cardiovascular no estudo EMPA-REG OUTCOME.",
      },
    ],
    contraindications: ["Hipersensibilidade ao fármaco", "Doença renal em estágio terminal / Diálise"],
    warnings: [
      "Cetoacidose euglicêmica",
      "Infecções do trato genitourinário e sepse urinária",
      "Hipotensão sintomática em pacientes hipovolêmicos ou idosos frágeis",
    ],
    interactions: [
      "Diuréticos (efeito sinérgico de desidratação e depleção volêmica)",
      "Hipoglicemiantes secretagogos de insulina (risco aumentado de hipoglicemia)",
    ],
    monitoring: [
      "Glicemia, HbA1c, PA e peso corporal",
      "Creatinina sérica e TFG no início e durante o seguimento",
    ],
    sources: [
      { title: "EMPEROR-Reduced and EMPEROR-Preserved Trials", organization: "NEJM" },
      { title: "KDIGO Clinical Practice Guideline for Diabetes Management in CKD", organization: "KDIGO" },
    ],
    reviewStatus: "reviewed",
    notes: "Primeiro iSGLT2 a demonstrar benefício conclusivo de sobrevida em insuficiência cardíaca com fração de ejeção preservada (ICFEp).",
  },

  // ==========================================
  // 3. MODULADORES DO SRAA: IECAs
  // ==========================================
  {
    id: "enalapril",
    genericName: "Maleato de Enalapril",
    brandNames: ["Renitec", "Vasopril", "Eupressin"],
    therapeuticClass: "Anti-hipertensivo / Inibidor da Enzima Conversora de Angiotensina (IECA)",
    mechanism:
      "Pró-fármaco hidrolisado a enalaprilat; inibe competitivamente a ECA, suprimindo a formação de angiotensina II, reduzindo a secreção de aldosterona e retardando a degradação da bradicinina.",
    presentations: ["Comprimidos de 5 mg, 10 mg e 20 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Hipertensão Arterial Sistêmica",
        route: "Via Oral",
        presentation: "Comprimidos 5 mg, 10 mg, 20 mg",
        initial: "5 mg a 10 mg, 1x/dia (ou 2,5 mg em idosos/hipovolêmicos)",
        titration: "Dobrar ou ajustar a dose a cada 1 a 2 semanas conforme alvos de PA",
        usual: "10 mg a 20 mg/dia, tomados em 1 ou fracionados em 2 vezes",
        interval: "A cada 12 horas ou 24 horas",
        target: "20 mg a 40 mg/dia",
        maximum: "40 mg/dia",
        duration: "Contínua",
        renalAdjustment: "TFG 30-80: 5 mg inicial (máx 40 mg). TFG < 30: 2,5 mg inicial (máx 20 mg). Hemodiálise: 2,5 mg nos dias de diálise.",
        hepaticAdjustment: "Conversão metabólica a enalaprilat pode estar lentificada; sem necessidade de ajuste posológico primário.",
        notes: "O fracionamento em 12/12h previne escape pressórico no final do período de dose.",
      },
      {
        population: "Adultos",
        indication: "Insuficiência Cardíaca com Fração de Ejeção Reduzida (ICFEr)",
        route: "Via Oral",
        presentation: "Comprimidos 2,5 mg (partido), 5 mg, 10 mg",
        initial: "2,5 mg, a cada 12 horas",
        titration: "Dobrar a dose a cada 2 a 4 semanas conforme PA, função renal e calemia",
        usual: "10 mg, a cada 12 horas",
        interval: "A cada 12 horas",
        target: "10 mg a 20 mg, a cada 12 horas (dose de ensaio clínico CONSENSUS/SOLVD)",
        maximum: "40 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Iniciar com 1,25 mg 12/12h se TFG < 30 mL/min.",
        hepaticAdjustment: "Sem restrição específica.",
        notes: "Titular rigorosamente até a dose alvo dos estudos para redução de morbimortalidade.",
      },
    ],
    contraindications: [
      "Histórico de angioedema prévio associado a IECA",
      "Angioedema hereditário ou idiopático",
      "Uso concomitante com Sacubitril/Valsartana (exige washout obrigatório de 36 horas)",
      "Estenose bilateral da artéria renal ou em rim único",
      "Gestação (teratogênico em todos os trimestres)",
    ],
    warnings: [
      "Tosse seca persistente mediada por bradicinina e substância P em 5 a 20% dos pacientes",
      "Hipercalemia, particularmente quando associado a suplementos de potássio ou poupadores de K+",
      "Hipotensão severa de primeira dose em pacientes previamente depletados de sódio/volume",
    ],
    interactions: [
      "Espironolactona e suplementos de potássio (risco severo de hipercalemia)",
      "AINEs (antagonizam o efeito vasodilatador e aumentam risco de injúria renal aguda)",
      "Lítio (reduz a depuração renal do lítio, elevando risco de intoxicação)",
    ],
    monitoring: [
      "Creatinina sérica e potássio antes do início e 1-2 semanas após cada incremento de dose",
      "Pressão arterial postural",
    ],
    sources: [
      { title: "SOLVD and CONSENSUS Trials", organization: "NEJM" },
      { title: "Diretrizes Brasileiras de Hipertensão Arterial", organization: "SBC / SBH" },
    ],
    reviewStatus: "reviewed",
    notes: "Elevação da creatinina de até 30% em relação ao basal após início é reflexo hemodinâmico esperado e aceitável.",
  },
  {
    id: "captopril",
    genericName: "Captopril",
    brandNames: ["Capoten"],
    therapeuticClass: "Anti-hipertensivo / Inibidor da ECA",
    mechanism: "Inibição competitiva da enzima conversora de angiotensina I em angiotensina II. Possui grupo sulfidrila e início de ação rápido com meia-vida curta.",
    presentations: ["Comprimidos de 12,5 mg, 25 mg e 50 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Hipertensão Arterial Sistêmica",
        route: "Via Oral",
        presentation: "Comprimidos 25 mg e 50 mg",
        initial: "12,5 mg a 25 mg, 2 a 3 vezes ao dia (1h antes das refeições)",
        titration: "Aumentar em intervalos de 1 a 2 semanas conforme resposta pressórica",
        usual: "25 mg a 50 mg, a cada 8 ou 12 horas",
        interval: "A cada 8 horas ou 12 horas",
        target: "50 mg, a cada 8 horas",
        maximum: "150 mg/dia (excepcionalmente 450 mg/dia em hipertensão refratária grave)",
        duration: "Contínua",
        renalAdjustment: "Reduzir dose ou ampliar intervalo se TFG < 50 mL/min.",
        hepaticAdjustment: "Sem restrição direta, metabolização hepática parcial.",
        notes: "Alimentos reduzem a biodisponibilidade em 30 a 40%; administrar 1 hora antes das refeições.",
      },
    ],
    contraindications: ["Mesmas contraindicações de classe dos IECAs (angioedema, estenose bilateral de artéria renal, gestação)."],
    warnings: ["Maior risco de disgeusia (perda do paladar) e rash cutâneo devido ao radical sulfidrila."],
    interactions: ["AINEs, sais de potássio, imunossupressores (risco de neutropenia)."],
    monitoring: ["PA, hemograma periódico em pacientes com colagenoses/insuficiência renal, função renal e eletrólitos."],
    sources: [{ title: "Goodman & Gilman: As Bases Farmacológicas da Terapêutica", organization: "McGraw-Hill" }],
    reviewStatus: "reviewed",
    notes: "Uso predominantemente histórico ou hospitalar em descompensações agudas devido à posologia incômoda de três tomadas diárias.",
  },
  {
    id: "ramipril",
    genericName: "Ramipril",
    brandNames: ["Triatec", "Altace"],
    therapeuticClass: "Anti-hipertensivo / Inibidor da ECA",
    mechanism: "Pró-fármaco lipofílico convertido em ramiprilat, inibidor potente e de longa duração da ECA tecidual e plasmática.",
    presentations: ["Cápsulas/Comprimidos de 2,5 mg, 5 mg e 10 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Prevenção Cardiovascular Secundária / Alto Risco (Ensaio HOPE)",
        route: "Via Oral",
        presentation: "Comprimidos 2,5 mg, 5 mg, 10 mg",
        initial: "2,5 mg, 1x/dia, por 1 semana",
        titration: "Aumentar para 5 mg 1x/dia por 3 semanas, seguido de escalonamento para dose alvo",
        usual: "10 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "10 mg, 1x/dia",
        maximum: "10 mg/dia",
        duration: "Contínua",
        renalAdjustment: "TFG < 30 mL/min: dose máxima de 5 mg/dia.",
        hepaticAdjustment: "Iniciar com dose de 1,25 mg em insuficiência hepática.",
        notes: "Fármaco padrão de referência para redução de IAM, AVC e morte cardiovascular em pacientes de alto risco.",
      },
    ],
    contraindications: ["Contraindicações universais de IECA."],
    warnings: ["Hipotensão, hipercalemia, tosse crônica."],
    interactions: ["Diuréticos espoliadores/poupadores de potássio, lítio, aliscireno."],
    monitoring: ["PA, ureia, creatinina, potássio sérico."],
    sources: [{ title: "HOPE Study Investigators", organization: "NEJM" }],
    reviewStatus: "reviewed",
    notes: "Excelente penetração tecidual e estabilidade de bloqueio do SRAA por 24 horas.",
  },

  // ==========================================
  // 4. MODULADORES DO SRAA: BRAS (ARA-II)
  // ==========================================
  {
    id: "losartana",
    genericName: "Losartana Potássica",
    brandNames: ["Cozaar", "Aradois", "Corus", "Losatec"],
    therapeuticClass: "Anti-hipertensivo / Bloqueador do Receptor de Angiotensina II (BRA)",
    mechanism:
      "Antagonismo competitivo e seletivo dos receptores AT1 da angiotensina II, bloqueando vasoconstrição e secreção de aldosterona sem inibir a degradação de bradicinina.",
    presentations: ["Comprimidos revestidos de 25 mg, 50 mg e 100 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Hipertensão Arterial e Nefroproteção no DM2",
        route: "Via Oral",
        presentation: "Comprimidos 50 mg e 100 mg",
        initial: "50 mg, 1x/dia (25 mg se idoso ou depleção de volume)",
        titration: "Aumentar para 100 mg em tomada única ou fracionado a cada 12h após 3-4 semanas se necessário",
        usual: "50 mg a 100 mg, 1x/dia",
        interval: "A cada 24 horas (ou 12/12h)",
        target: "100 mg/dia",
        maximum: "100 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Sem necessidade de redução inicial de dose em DRC sem depleção de volume.",
        hepaticAdjustment: "Iniciar com 25 mg 1x/dia em histórico de cirrose ou disfunção hepática.",
        notes: "Possui discreto efeito uricosúrico intrínseco pela inibição do transportador URAT1 renal.",
      },
      {
        population: "Adultos",
        indication: "Insuficiência Cardíaca com Fração de Ejeção Reduzida (ICFEr)",
        route: "Via Oral",
        presentation: "Comprimidos 50 mg e 100 mg",
        initial: "25 mg a 50 mg, 1x/dia",
        titration: "Dobrar a dose a cada 2 a 4 semanas visando o teto com validação de sobrevida",
        usual: "100 mg a 150 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "150 mg, 1x/dia (Dose alvo do estudo HEAAL)",
        maximum: "150 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Monitorar calemia e creatinina.",
        hepaticAdjustment: "Ajuste na disfunção hepática.",
        notes: "Doses de 50 mg não são consideradas protetoras plenas para mortalidade em ICFEr.",
      },
    ],
    contraindications: [
      "Hipersensibilidade à substância",
      "Uso combinado com Aliscireno em diabéticos ou pacientes com disfunção renal moderada/grave",
      "Gestação e lactação",
      "Estenose bilateral grave de artéria renal",
    ],
    warnings: [
      "Hipercalemia, principalmente em pacientes nefropatas ou sob terapia com espironolactona",
      "Hipotensão sintomática em indivíduos com hipovolemia prévia",
      "Incidência de tosse seca é drasticamente inferior à dos IECAs (< 1%)",
    ],
    interactions: [
      "Inibidores da CYP2C9 e CYP3A4 podem reduzir a formação do metabólito ativo EXP-3174",
      "AINEs (redução do efeito anti-hipertensivo e nefrotoxicidade somada)",
      "Poupadores de potássio e trimetoprima-sulfametoxazol (potencializam hipercalemia)",
    ],
    monitoring: ["Creatinina sérica, TFG e potássio sérico basal e 15 dias após ajuste.", "PA ambulatorial."],
    sources: [
      { title: "RENAAL Trial", organization: "NEJM" },
      { title: "HEAAL Study", organization: "The Lancet" },
    ],
    reviewStatus: "reviewed",
    notes: "Alternativa padrão mandatória aos IECAs quando há tosse seca intolerável ou história de angioedema bradicinina-dependente.",
  },
  {
    id: "valsartana",
    genericName: "Valsartana",
    brandNames: ["Diovan", "Tareg"],
    therapeuticClass: "Anti-hipertensivo / BRA",
    mechanism: "Bloqueio potente e altamente seletivo dos receptores AT1 sem afinidade residual significativa para receptores AT2.",
    presentations: ["Comprimidos revestidos de 80 mg, 160 mg e 320 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Insuficiência Cardíaca (ICFEr)",
        route: "Via Oral",
        presentation: "Comprimidos 80 mg e 160 mg",
        initial: "40 mg, a cada 12 horas",
        titration: "Dobrar a cada 2 a 4 semanas até alcançar a tolerância hemodinâmica máxima",
        usual: "80 mg a 160 mg, a cada 12 horas",
        interval: "A cada 12 horas",
        target: "160 mg, a cada 12 horas (320 mg/dia total)",
        maximum: "320 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Sem necessidade de redução na DRC sem estenose de artéria renal.",
        hepaticAdjustment: "Não exceder 80 mg/dia em disfunção hepática leve a moderada.",
        notes: "Dose do estudo Val-HeFT para melhora de sobrevida e remodelamento ventricular.",
      },
    ],
    contraindications: ["Gestação, associação com aliscireno em DM2, cirrose biliar."],
    warnings: ["Risco de hipotensão severa na primeira dose se associada a altas doses de furosemida."],
    interactions: ["Lítio, suplementos de potássio, diuréticos poupadores de K+."],
    monitoring: ["Pressão arterial, potássio sérico, ureia e creatinina."],
    sources: [{ title: "Val-HeFT Trial", organization: "NEJM" }],
    reviewStatus: "reviewed",
    notes: "Componente essencial da combinação com sacubitril (ARNI) para tratamento de ponta na ICFEr.",
  },
  {
    id: "candesartana",
    genericName: "Candesartana Cilexetila",
    brandNames: ["Blopress", "Atacand"],
    therapeuticClass: "Anti-hipertensivo / BRA",
    mechanism: "Pró-fármaco hidrolisado durante a absorção gastrointestinal a candesartana, que exibe dissociação lenta e ligação insuperável aos receptores AT1.",
    presentations: ["Comprimidos de 8 mg, 16 mg e 32 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "ICFEr (Programa CHARM) e Hipertensão",
        route: "Via Oral",
        presentation: "Comprimidos 8 mg, 16 mg, 32 mg",
        initial: "4 mg a 8 mg, 1x/dia",
        titration: "Dobrar em intervalos de 2 semanas conforme tolerado",
        usual: "16 mg a 32 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "32 mg, 1x/dia",
        maximum: "32 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Sem ajuste específico, titular sob vigilância de TFG e K+.",
        hepaticAdjustment: "Considerar dose inicial de 4 mg em doença hepática moderada.",
        notes: "Maior afinidade tecidual e ligação mais duradoura ao receptor AT1 entre os BRAs.",
      },
    ],
    contraindications: ["Gravidez, hipersensibilidade, colestase grave."],
    warnings: ["Hipotensão sintomática, hipercalemia."],
    interactions: ["Medicamentos que elevam o potássio sérico, AINEs."],
    monitoring: ["Calemia, função renal seriada e controle pressórico."],
    sources: [{ title: "CHARM Program", organization: "The Lancet" }],
    reviewStatus: "reviewed",
    notes: "Demonstrou expressiva eficácia na redução de morte cardiovascular e hospitalizações por IC.",
  },

  // ==========================================
  // 5. INIBIDORES DA HMG-CoA REDUTASE (ESTATINAS)
  // ==========================================
  {
    id: "atorvastatina",
    genericName: "Atorvastatina Cálcica",
    brandNames: ["Lipitor", "Citalor", "Amplictil"],
    therapeuticClass: "Hipolipemiante / Inibidor da HMG-CoA Redutase",
    mechanism:
      "Inibição competitiva da hidroximetilglutaril-coenzima A (HMG-CoA) redutase. O esgotamento do colesterol intracelular estimula SREBP-2 e up-regulation de receptores de LDL na membrana do hepatócito, reduzindo LDL-C sérico e triglicerídeos.",
    presentations: ["Comprimidos revestidos de 10 mg, 20 mg, 40 mg e 80 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Dislipidemia / Prevenção Cardiovascular Primária e Secundária",
        route: "Via Oral",
        presentation: "Comprimidos 10 mg, 20 mg, 40 mg, 80 mg",
        initial:
          "Moderada intensidade: 10 mg a 20 mg, 1x/dia. Alta intensidade (SCA, alto risco cardiovascular): 40 mg a 80 mg, 1x/dia.",
        titration: "Ajustar dose após 4 a 12 semanas conforme perfil lipídico e metas individualizadas",
        usual: "20 mg a 80 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "Redução de ≥ 50% no LDL-C basal (esquema de alta intensidade)",
        maximum: "80 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Não requer ajuste na insuficiência renal crônica (clearance predominantemente biliar/fecal).",
        hepaticAdjustment: "Contraindicada em doença hepática ativa ou elevações persistentes e inexplicadas de transaminases.",
        notes: "Meia-vida de eliminação de 14h com metabólitos ativos que mantêm inibição por 20 a 30h. Pode ser ingerida a qualquer hora do dia.",
      },
    ],
    contraindications: [
      "Doença hepática ativa ou elevações inexplicadas das transaminases (> 3x LSN)",
      "Gravidez e amamentação (categoria X)",
      "Uso concomitante com inibidores potentes do CYP3A4 em altas doses",
    ],
    warnings: [
      "Miopatia tóxica e risco de rabdomiólise (atenção a mialgias inexplicadas, fraqueza proximal e urina escura)",
      "Discreto aumento dose-dependente na incidência de novo diagnóstico de DM2",
      "Elevação transitória de transaminases hepáticas",
    ],
    interactions: [
      "Inibidores da CYP3A4 (claritromicina, cetoconazol, ritonavir, suco de toranja/grapefruit) elevam toxicidade",
      "Genfibrozila (aumento severo de risco de rabdomiólise; preferir fenofibrato se associação for imperativa)",
      "Ciclosporina (aumenta expressivamente a área sob a curva da atorvastatina)",
    ],
    monitoring: [
      "Painel lipídico (CT, LDL-C, HDL-C, TG) após 4-12 semanas de início ou titulação",
      "ALT/AST basais antes do início do tratamento",
      "Creatinoquinase (CK) apenas se sintomas de mialgia, fadiga muscular ou fraqueza muscular referida",
    ],
    sources: [
      { title: "ACC/AHA Guideline on the Management of Blood Cholesterol", organization: "Circulation" },
      { title: "Atualização da Diretriz Brasileira de Dislipidemias", organization: "SBC" },
    ],
    reviewStatus: "reviewed",
    notes: "Estatina de alta intensidade amplamente validada pós-Síndrome Coronariana Aguda (estudo PROVE-IT TIMI 22).",
  },
  {
    id: "rosuvastatina",
    genericName: "Rosuvastatina Cálcica",
    brandNames: ["Crestor", "Vivacor", "Rosucol"],
    therapeuticClass: "Hipolipemiante / Inibidor da HMG-CoA Redutase",
    mechanism: "Inibição seletiva e competitiva da HMG-CoA redutase. Apresenta caráter hidrofílico, com baixa captação em tecidos extra-hepáticos.",
    presentations: ["Comprimidos revestidos de 5 mg, 10 mg, 20 mg e 40 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Dislipidemia de Alto Risco / Prevenção Aterotrombótica",
        route: "Via Oral",
        presentation: "Comprimidos 5 mg, 10 mg, 20 mg, 40 mg",
        initial: "Moderada intensidade: 5 mg a 10 mg, 1x/dia. Alta intensidade: 20 mg a 40 mg, 1x/dia.",
        titration: "Avaliar resposta em 4 a 8 semanas antes de titular",
        usual: "10 mg a 20 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "Redução de ≥ 50% de LDL-C (com 20 mg a 40 mg/dia)",
        maximum: "40 mg/dia (iniciar com 5 mg em descendentes asiáticos)",
        duration: "Contínua",
        renalAdjustment: "TFG < 30 mL/min: iniciar com 5 mg/dia; dose máxima restrita a 10 mg/dia.",
        hepaticAdjustment: "Contraindicada em hepatopatia ativa.",
        notes: "Metabolismo independente do CYP3A4 (metabolizada fracamente pelo CYP2C9), menor propensão a interações.",
      },
    ],
    contraindications: ["Hepatopatia ativa, gravidez, miopatia prévia, insuficiência renal severa (para dose de 40 mg)."],
    warnings: ["Proteinúria tubular transitória em doses muito altas (40 mg), rabdomiólise."],
    interactions: ["Antiácidos à base de alumínio/magnésio diminuem absorção, ciclosporina eleva níveis séricos."],
    monitoring: ["Perfil lipídico de seguimento, enzimas hepáticas, TFG."],
    sources: [{ title: "JUPITER Trial", organization: "NEJM" }],
    reviewStatus: "reviewed",
    notes: "Apresenta a maior potência miligrama a miligrama na redução de LDL-C da classe das estatinas.",
  },
  {
    id: "sinvastatina",
    genericName: "Sinvastatina",
    brandNames: ["Zocor", "Sinvasmax", "Vaslip"],
    therapeuticClass: "Hipolipemiante / Inibidor da HMG-CoA Redutase",
    mechanism: "Pró-fármaco lactônico lipofílico inativo, hidrolisado in vivo para a forma beta-hidroxiácida inibidora da HMG-CoA redutase.",
    presentations: ["Comprimidos revestidos de 10 mg, 20 mg e 40 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Dislipidemia e Prevenção Cardiovascular Primária/Secundária",
        route: "Via Oral",
        presentation: "Comprimidos 10 mg, 20 mg, 40 mg",
        initial: "20 mg a 40 mg, 1x/dia, administrados OBRIGATORIAMENTE à noite",
        titration: "Ajustar em intervalos não inferiores a 4 semanas",
        usual: "20 mg a 40 mg à noite",
        interval: "A cada 24 horas (noturno)",
        target: "Redução de 30% a 45% do LDL-C (intensidade moderada)",
        maximum: "40 mg/dia (a dose de 80 mg/dia é formalmente desaconselhada pelo FDA/Anvisa)",
        duration: "Contínua",
        renalAdjustment: "TFG < 30 mL/min: iniciar com 10 mg/dia e titular cautelosamente.",
        hepaticAdjustment: "Contraindicada na hepatopatia aguda.",
        notes: "Meia-vida ultracurta (2 a 3h); pico de síntese do colesterol ocorre de madrugada, exigindo administração noturna.",
      },
    ],
    contraindications: ["Gravidez, amamentação, uso concomitante com antifúngicos azólicos, macrolídeos e genfibrozila."],
    warnings: ["Risco elevado de rabdomiólise se utilizada em doses elevadas (80 mg) ou associada a inibidores de CYP3A4."],
    interactions: ["Amiodarona, anlodipino e verapamil elevam os níveis séricos (limitar dose de sinvastatina a 20 mg se em uso conjunto)."],
    monitoring: ["Lipidograma basal e pós-tratamento, transaminases."],
    sources: [{ title: "Scandinavian Simvastatin Survival Study (4S)", organization: "The Lancet" }],
    reviewStatus: "reviewed",
    notes: "Fármaco histórico da classe, amplamente disponível na atenção primária básica.",
  },

  // ==========================================
  // 6. DIURÉTICOS (TIAZÍDICOS, DE ALÇA E ARM)
  // ==========================================
  {
    id: "hidroclorotiazida",
    genericName: "Hidroclorotiazida",
    brandNames: ["Clorana", "Drenol"],
    therapeuticClass: "Diurético Tiazídico / Anti-hipertensivo",
    mechanism: "Inibição do cotransportador de sódio e cloro (NCC / Na+/Cl-) no túbulo contorcido distal, promovendo natriurese moderada e vasodilatação a longo prazo.",
    presentations: ["Comprimidos de 25 mg e 50 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Hipertensão Arterial Sistêmica",
        route: "Via Oral",
        presentation: "Comprimidos 25 mg",
        initial: "12,5 mg a 25 mg, 1x/dia, pela manhã",
        titration: "Manter dose entre 12,5 mg e 25 mg. Doses superiores não aumentam controle pressórico",
        usual: "12,5 mg a 25 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "25 mg/dia",
        maximum: "50 mg/dia (não recomendada em monoterapia)",
        duration: "Contínua",
        renalAdjustment: "Perde eficácia natriurética relevante quando a TFG cai abaixo de 30 mL/min.",
        hepaticAdjustment: "Monitorar risco de encefalopatia por distúrbios hidroeletrolíticos.",
        notes: "Curva dose-resposta plana para PA acima de 25 mg, mas ascendente para espoliação de potássio.",
      },
    ],
    contraindications: ["Anúria, hipersensibilidade a derivados de sulfonamidas, hipocalemia grave refratária."],
    warnings: ["Hipocalemia, hiponatremia, hipomagnesemia, hiperuricemia (pode precipitar crises de gota) e hiperglicemia."],
    interactions: ["Lítio (aumenta toxicidade do lítio por redução de excreção), AINEs (reduzem efeito diurético)."],
    monitoring: ["Sódio, potássio, ácido úrico e glicemia de jejum após 2 a 4 semanas de início."],
    sources: [{ title: "ALLHAT Officers and Coordinators", organization: "JAMA" }],
    reviewStatus: "reviewed",
    notes: "Frequentemente combinada a doses fixas com IECAs ou BRAs para sinergismo farmacodinâmico e neutralização da retenção de K+.",
  },
  {
    id: "clortalidona",
    genericName: "Clortalidona",
    brandNames: ["Higroton"],
    therapeuticClass: "Diurético Tiazida-Like / Anti-hipertensivo",
    mechanism: "Inibição do cotransportador Na+/Cl- distal com meia-vida biológica de 40 a 60 horas e inibição prolongada da anidrase carbônica eritrocitária.",
    presentations: ["Comprimidos de 12,5 mg, 25 mg e 50 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Hipertensão Arterial Sistêmica",
        route: "Via Oral",
        presentation: "Comprimidos 12,5 mg e 25 mg",
        initial: "12,5 mg, 1x/dia, pela manhã",
        titration: "Pode ser aumentada para 25 mg/dia após 4 semanas",
        usual: "12,5 mg a 25 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "12,5 mg a 25 mg/dia",
        maximum: "50 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Eficácia atenuada com TFG < 30 mL/min.",
        hepaticAdjustment: "Cautela com encefalopatia hepática.",
        notes: "Mais potente por miligrama e com proteção cardiovascular mais documentada em ensaios que a HCTZ.",
      },
    ],
    contraindications: ["Insuficiência renal anúrica, gota articular aguda descompensada."],
    warnings: ["Maior propensão a hipocalemia sintomática e hiponatremia em comparação à hidroclorotiazida."],
    interactions: ["Digitálicos (aumento da arritmogênese se houver hipocalemia associada)."],
    monitoring: ["Eletrólitos séricos (sódio e potássio) seriados."],
    sources: [{ title: "SHEP and ALLHAT Studies", organization: "JAMA" }],
    reviewStatus: "reviewed",
    notes: "Tiazídico preferencial nas diretrizes norte-americanas (ACC/AHA) pela estabilidade de controle ao longo das 24h.",
  },
  {
    id: "indapamida",
    genericName: "Indapamida",
    brandNames: ["Natrilix", "Natrilix SR"],
    therapeuticClass: "Diurético Tiazida-Like / Vasodilatador",
    mechanism: "Inibição da reabsorção tubular de sódio no néfron distal somada a um efeito vasodilatador vascular direto por modulação do influxo de cálcio.",
    presentations: ["Comprimidos de liberação imediata: 2,5 mg", "Comprimidos de liberação prolongada (SR): 1,5 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Hipertensão Arterial (Especialmente no Idoso)",
        route: "Via Oral",
        presentation: "Comprimido SR 1,5 mg",
        initial: "1,5 mg (SR), 1x/dia, pela manhã",
        titration: "Dose fixa; formulação SR dispensa titulação",
        usual: "1,5 mg/dia",
        interval: "A cada 24 horas",
        target: "1,5 mg/dia",
        maximum: "2,5 mg/dia (IR) ou 1,5 mg/dia (SR)",
        duration: "Contínua",
        renalAdjustment: "Pouco efetiva se TFG < 30 mL/min.",
        hepaticAdjustment: "Sem necessidade de titulação em graus leves.",
        notes: "Perfil neutro sobre lipídios plasmáticos e resistência à insulina.",
      },
    ],
    contraindications: ["Hipersensibilidade a sulfamidas, encefalopatia hepática grave."],
    warnings: ["Hipocalemia discreta, menor incidência de alterações metabólicas."],
    interactions: ["Lítio, antiarrítmicos predisponentes a Torsades de Pointes."],
    monitoring: ["Pressão arterial, potássio sérico."],
    sources: [{ title: "HYVET Trial", organization: "NEJM" }],
    reviewStatus: "reviewed",
    notes: "Fármaco que demonstrou redução consistente de AVC e mortalidade em hipertensos muito idosos (> 80 anos).",
  },
  {
    id: "furosemida",
    genericName: "Furosemida",
    brandNames: ["Lasix"],
    therapeuticClass: "Diurético de Alça",
    mechanism: "Inibição potente do cotransportador Na+/K+/2Cl- na porção ascendente espessa da alça de Henle, bloqueando a capacidade de concentração medular.",
    presentations: ["Comprimidos de 40 mg", "Ampolas de 20 mg/2 mL"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Congestão e Sobrecarga Volêmica na Insuficiência Cardíaca e DRC",
        route: "Via Oral / Via Intravenosa",
        presentation: "Comprimidos 40 mg / Ampolas 20 mg/2 mL",
        initial: "Ambulatorial: 20 mg a 40 mg, 1x/dia pela manhã. Agudo (IV): 20 mg a 40 mg em bolus lento.",
        titration: "Dobrar a dose oral ou IV a cada 2 a 4 horas no ambiente agudo até obter taxa diurética alvo",
        usual: "40 mg a 80 mg/dia fracionados em 1 ou 2 tomadas",
        interval: "A cada 12 horas ou 24 horas",
        target: "Manutenção do estado euvolêmico com a menor dose diária possível",
        maximum: "Até 240 mg a 600 mg/dia em síndromes nefróticas graves ou DRC terminal sob estrita vigilância",
        duration: "Conforme persistência da sobrecarga volêmica",
        renalAdjustment: "Doses significativamente mais altas são necessárias em pacientes com baixa TFG para alcançar a alça intraluminal.",
        hepaticAdjustment: "Titular cautelosamente em cirróticos pelo risco de síndrome hepatorrenal.",
        notes: "Biodisponibilidade oral média de ~50% (40 mg VO equivalem a cerca de 20 mg IV).",
      },
    ],
    contraindications: ["Anúria irresponsiva a teste de dose, coma hepático, hipovolemia ou desidratação severa."],
    warnings: [
      "Ototoxicidade (especialmente em infusões IV rápidas ou combinada a aminoglicosídeos)",
      "Depleção hidroeletrolítica maciça: hipocalemia, hipomagnesemia, hiponatremia, alcalose metabólica hipoclorêmica",
    ],
    interactions: ["Aminoglicosídeos (ototoxicidade sinérgica), anti-inflamatórios (reduzem resposta natriurética)."],
    monitoring: ["Peso diário, balanço hídrico, função renal, sódio, potássio, magnésio e cloro séricos."],
    sources: [{ title: "DOSE Trial", organization: "NEJM" }],
    reviewStatus: "reviewed",
    notes: "O objetivo na insuficiência cardíaca é o alívio sintomático de congestão pulmonar e periférica; não reduz mortalidade por si só.",
  },
  {
    id: "espironolactona",
    genericName: "Espironolactona",
    brandNames: ["Aldactone"],
    therapeuticClass: "Antagonista do Receptor de Mineralocorticoide (ARM) / Poupador de Potássio",
    mechanism: "Antagonismo competitivo específico da aldosterona nos receptores mineralocorticoides dos túbulos coletores renais, promovendo espoliação de sódio e retenção de potássio e prótons.",
    presentations: ["Comprimidos de 25 mg, 50 mg e 100 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Insuficiência Cardíaca com Fração de Ejeção Reduzida (ICFEr)",
        route: "Via Oral",
        presentation: "Comprimidos 25 mg",
        initial: "12,5 mg a 25 mg, 1x/dia",
        titration: "Aumentar para 50 mg 1x/dia após 4 a 8 semanas se potássio sérico < 5,0 mEq/L e função renal estável",
        usual: "25 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "50 mg, 1x/dia",
        maximum: "50 mg/dia para ICFEr",
        duration: "Contínua",
        renalAdjustment: "Não iniciar se TFG < 30 mL/min/1,73m² ou creatinina > 2,5 mg/dL (homens) / > 2,0 mg/dL (mulheres).",
        hepaticAdjustment: "Sem restrição direta; amplamente usada na ascite cirrótica.",
        notes: "Reduz morbimortalidade e remodelamento fibrótico cardíaco comprovado no estudo RALES.",
      },
      {
        population: "Adultos",
        indication: "Hipertensão Resistente (4º fármaco)",
        route: "Via Oral",
        presentation: "Comprimidos 25 mg e 50 mg",
        initial: "25 mg, 1x/dia",
        titration: "Pode ser aumentada para 50 mg/dia após 4 semanas",
        usual: "25 mg a 50 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "25 mg a 50 mg/dia",
        maximum: "50 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Monitorar calemia rigorosamente se TFG entre 30 e 50 mL/min.",
        hepaticAdjustment: "Seguro se eletrólitos preservados.",
        notes: "Estudo PATHWAY-2 demonstrou superioridade clara como quarto fármaco na HAS resistente.",
      },
    ],
    contraindications: ["Hipercalemia inicial (> 5,0 mEq/L), insuficiência renal aguda ou TFG < 30 mL/min, Doença de Addison."],
    warnings: [
      "Hipercalemia severa com risco de arritmias ventriculares",
      "Ginecomastia dolorosa, mastodinia e disfunção erétil decorrentes do bloqueio de receptores androgênicos",
    ],
    interactions: ["IECAs, BRAs, suplementos de potássio, sulfametoxazol-trimetoprima (elevação crítica do potássio)."],
    monitoring: ["Potássio sérico e creatinina em 1 semana, 1 mês, 3 meses e depois a cada 6 meses."],
    sources: [{ title: "RALES Trial", organization: "NEJM" }, { title: "PATHWAY-2 Study", organization: "The Lancet" }],
    reviewStatus: "reviewed",
    notes: "Um dos 4 pilares da ICFEr; em caso de ginecomastia severa, sua substituta direta é a eplerenona.",
  },

  // ==========================================
  // 7. BLOQUEADORES DOS CANAIS DE CÁLCIO (BCC)
  // ==========================================
  {
    id: "anlodipino",
    genericName: "Besilato de Anlodipino",
    brandNames: ["Norvasc", "Cordarex", "Pressat"],
    therapeuticClass: "Anti-hipertensivo / Bloqueador dos Canais de Cálcio Dihidropiridínico",
    mechanism: "Bloqueio seletivo do influxo transmembrana de íons cálcio via canais tipo L na musculatura lisa vascular periférica e coronariana, gerando vasodilatação arteriolar.",
    presentations: ["Comprimidos de 5 mg e 10 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Hipertensão Arterial e Angina Estável",
        route: "Via Oral",
        presentation: "Comprimidos 5 mg e 10 mg",
        initial: "5 mg, 1x/dia (2,5 mg em idosos frágeis ou insuficiência hepática)",
        titration: "Aumentar para 10 mg/dia após 1 a 2 semanas se meta pressórica não for atingida",
        usual: "5 mg a 10 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "5 mg a 10 mg/dia",
        maximum: "10 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Não requer nenhum ajuste em falência renal ou diálise.",
        hepaticAdjustment: "Metabolismo exclusivamente hepático; titular lentamente com dose inicial de 2,5 mg.",
        notes: "Excelente meia-vida biológica (35 a 50 horas), garantindo controle pressórico estável.",
      },
    ],
    contraindications: ["Hipotensão severa, choque cardiogênico, estenose aórtica crítica sintomática."],
    warnings: [
      "Edema maleolar e pré-tibial dose-dependente (transudação por vasodilatação pré-capilar, sem sobrecarga de volume)",
      "Cefaleia e rubor facial nas primeiras semanas",
    ],
    interactions: [
      "Sinvastatina (limitar dose de sinvastatina a 20 mg/dia pela inibição competitiva da CYP3A4)",
      "Inibidores fortes de CYP3A4 (cetoconazol, claritromicina) elevam os níveis séricos do anlodipino",
    ],
    monitoring: ["Inspeção de membros inferiores para edema, aferição rotineira de PA e frequência cardíaca."],
    sources: [{ title: "ALLHAT Study", organization: "JAMA" }],
    reviewStatus: "reviewed",
    notes: "A associação com IECA ou BRA reduz expressivamente a incidência de edema de membros inferiores.",
  },
  {
    id: "nifedipino",
    genericName: "Nifedipino",
    brandNames: ["Adalat OROS", "Adalat Retard"],
    therapeuticClass: "Bloqueador dos Canais de Cálcio Dihidropiridínico",
    mechanism: "Inibição potente do influxo de cálcio nos canais voltagem-dependentes vasculares arteriais.",
    presentations: ["Comprimidos de liberação prolongada / OROS: 20 mg, 30 mg e 60 mg", "Retard: 10 mg, 20 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Hipertensão Arterial e Fenômeno de Raynaud",
        route: "Via Oral",
        presentation: "Comprimidos OROS 30 mg e 60 mg",
        initial: "30 mg, 1x/dia (formulações OROS/GITS)",
        titration: "Ajustar em intervalos de 7 a 14 dias para 60 mg/dia",
        usual: "30 mg a 60 mg, 1x/dia",
        interval: "A cada 24 horas",
        target: "60 mg/dia",
        maximum: "90 mg a 120 mg/dia dependendo da formulação",
        duration: "Contínua",
        renalAdjustment: "Sem necessidade de redução posológica.",
        hepaticAdjustment: "Reduzir dose em hepatopatia.",
        notes: "O sistema OROS promove liberação osmótica constante ao longo de 24 horas.",
      },
    ],
    contraindications: [
      "Uso de formulações de liberação imediata (cápsula curta sublingual) em emergências hipertensivas (risco de morte/isquemia)",
      "Choque cardiovascular",
    ],
    warnings: ["Taquicardia reflexa com formulações de liberação não controlada, edema periférico."],
    interactions: ["Sulfato de magnésio parenteral (risco de hipotensão profunda e bloqueio neuromuscular)."],
    monitoring: ["Pressão arterial, presença de edema periférico."],
    sources: [{ title: "ACTION Trial", organization: "The Lancet" }],
    reviewStatus: "reviewed",
    notes: "Formulações de liberação rápida estão proscritas para controle de picos pressóricos.",
  },
  {
    id: "diltiazem",
    genericName: "Cloridrato de Diltiazem",
    brandNames: ["Cardizem", "Balcor"],
    therapeuticClass: "Bloqueador dos Canais de Cálcio Não-Dihidropiridínico (Benzotiazepina)",
    mechanism: "Bloqueio misto de canais de cálcio vasculares e cardíacos, reduzindo condução no nó atrioventricular, inotropismo e resistência vascular periférica.",
    presentations: ["Comprimidos de 30 mg e 60 mg", "Cápsulas de liberação prolongada de 90 mg, 120 mg, 180 mg, 240 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Controle de Frequência Cardíaca na Fibrilação Atrial e Angina",
        route: "Via Oral",
        presentation: "Comprimidos 60 mg / Liberação prolongada 180 mg",
        initial: "30 mg a 60 mg a cada 8h (IR) ou 120 mg a 180 mg 1x/dia (retard)",
        titration: "Ajustar a cada 1-2 dias conforme FC de repouso e PA",
        usual: "180 mg a 360 mg/dia",
        interval: "A cada 8 horas (IR) ou a cada 24 horas (retard)",
        target: "FC de repouso < 80-100 bpm",
        maximum: "360 mg a 480 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Sem ajuste direto necessário.",
        hepaticAdjustment: "Titular com cuidado por extenso metabolismo hepático de primeira passagem.",
        notes: "Contraindicado em pacientes com ICFEr pelo efeito inotrópico negativo.",
      },
    ],
    contraindications: ["Disfunção ventricular esquerda moderada a grave (ICFEr), BAV de 2º ou 3º grau, síndrome do nó sinusal."],
    warnings: ["Bradicardia sinusal, bloqueios atrioventriculares, descompensação de insuficiência cardíaca."],
    interactions: ["Betabloqueadores (sinergismo cardiodepressor severo), estatinas metabolizadas por CYP3A4."],
    monitoring: ["Eletrocardiograma (intervalo PR), frequência cardíaca e PA."],
    sources: [{ title: "AHA/ACC AF Guidelines", organization: "Circulation" }],
    reviewStatus: "reviewed",
    notes: "Opção para controle de FC em FA quando os betabloqueadores são contraindicados por broncoespasmo grave.",
  },
  {
    id: "verapamil",
    genericName: "Cloridrato de Verapamil",
    brandNames: ["Dilacoron"],
    therapeuticClass: "Bloqueador dos Canais de Cálcio Não-Dihidropiridínico (Fenilalquilamina)",
    mechanism: "Bloqueador potente com máxima cardiosseletividade sobre o nó sinusal, nó AV e miocárdio contrátil com menor efeito vasodilatador vascular periférico que dihidropiridinas.",
    presentations: ["Comprimidos de 80 mg e 120 mg", "Comprimidos retard de 120 mg e 240 mg"],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Taquiarritmias Supraventriculares e Angina",
        route: "Via Oral",
        presentation: "Comprimidos 80 mg / 120 mg / Retard 240 mg",
        initial: "80 mg a cada 8h ou 120 mg a 240 mg 1x/dia (retard)",
        titration: "Ajustar dose em intervalos semanais",
        usual: "240 mg a 360 mg/dia divididos",
        interval: "A cada 8 horas (IR) ou 24 horas (retard)",
        target: "Controle sintomático e manutenção do ritmo/frequência",
        maximum: "480 mg/dia",
        duration: "Contínua",
        renalAdjustment: "Sem necessidade de redução posológica primária.",
        hepaticAdjustment: "Reduzir dose para 20 a 30% da dose normal em cirrose descompensada.",
        notes: "Causa constipação intestinal grave em idosos por inibição motora do cólon.",
      },
    ],
    contraindications: ["Insuficiência cardíaca com fração de ejeção reduzida, choque cardiogênico, BAV avançado, WPW com FA."],
    warnings: ["Inotrópico negativo potente, bradipneia, constipação crônica pertinaz."],
    interactions: ["Digoxina (eleva em até 50-70% os níveis de digoxina), betabloqueadores (risco de assistolia)."],
    monitoring: ["ECG contínuo se uso IV, intervalo PR e PA."],
    sources: [{ title: "Goodman & Gilman", organization: "McGraw-Hill" }],
    reviewStatus: "reviewed",
    notes: "Fármaco potente para profilaxia de taquicardia paroxística supraventricular (TPSV).",
  },

  // ==========================================
  // 8. ANALGÉSICOS, ANTIPIRÉTICOS E AINES
  // ==========================================
  {
    id: "dipirona",
    genericName: "Dipirona Monoidratada (Metamizol)",
    brandNames: ["Novalgina", "Anador", "Lisador"],
    therapeuticClass: "Analgésico e Antipirético Não-Opioide",
    mechanism:
      "Ação analgésica central e periférica. Inibição de isoformas de COX-1/COX-2 e COX-3 atípicas no SNC, ativação de vias canabinoides endógenas (CB1) e do sistema inibitório descendente opioide e serotoninérgico.",
    presentations: [
      "Comprimidos de 500 mg e 1000 mg",
      "Gotas / Solução oral: 500 mg/mL (1 mL = 20 gotas)",
      "Solução oral concentrada: 50 mg/mL",
      "Ampolas injetáveis: 1000 mg/2 mL",
    ],
    doseProfiles: [
      {
        population: "Adultos e Adolescentes (> 15 anos ou > 53 kg)",
        indication: "Dor Aguda e Febre",
        route: "Via Oral / Via Intravenosa / Via Intramuscular",
        presentation: "Comprimidos 500 mg / 1000 mg; Solução 500 mg/mL; Ampolas 1 g/2 mL",
        initial: "500 mg a 1000 mg por tomada",
        titration: "Administrar conforme demanda respeitando os intervalos",
        usual: "500 mg a 1000 mg a cada 6 ou 8 horas",
        interval: "A cada 6 horas ou 8 horas",
        target: "Alívio álgico satisfatório (EVA < 3/10)",
        maximum: "4000 mg/dia (em ambiente hospitalar monitorado admite-se até 5000 mg/dia)",
        duration: "Curto prazo / Período da dor aguda ou febre",
        renalAdjustment: "Evitar doses máximas repetidas na insuficiência renal grave pelo acúmulo de metabólitos ativos (4-MAA).",
        hepaticAdjustment: "Reduzir dose em hepatopatias crônicas graves.",
        notes: "A administração intravenosa deve ser SEMPRE em infusão lenta (3 a 5 min ou diluída) para evitar colapso hemodinâmico hipotensivo.",
      },
      {
        population: "Pediátrico",
        indication: "Febre e Dor Infantil",
        route: "Via Oral",
        presentation: "Gotas 500 mg/mL (1 gota = 25 mg)",
        initial: "10 mg a 15 mg/kg por dose",
        titration: "Repetir a cada 6 a 8 horas se persistência",
        usual: "1 gota para cada 2 kg de peso (dose de 12,5 mg/kg) até 4x/dia",
        interval: "A cada 6 horas ou 8 horas",
        target: "Afebril e controle álgico",
        maximum: "60 mg/kg/dia ou teto de 2000 mg a 4000 mg/dia",
        duration: "Período agudo",
        renalAdjustment: "Sem restrição para cursos agudos breves.",
        hepaticAdjustment: "Evitar cursos prolongados.",
        notes: "Não utilizar em lactentes menores de 3 meses ou pesando menos de 5 kg.",
      },
    ],
    contraindications: [
      "Hipersensibilidade a pirazolonas",
      "Deficiência congênita de Glicose-6-Fosfato Desidrogenase (risco de hemólise aguda)",
      "Supressão de medula óssea ou histórico prévio de agranulocitose associada a metamizol",
      "Porfiria hepática aguda intermitente",
    ],
    warnings: [
      "Hipotensão arterial aguda dose-dependente mediada por relaxamento da musculatura lisa vascular em infusões IV rápidas",
      "Risco idiossincrático raríssimo de agranulocitose grave e anemia aplásica",
      "Reações cutâneas graves (Síndrome de Stevens-Johnson / NET)",
    ],
    interactions: [
      "Ciclosporina (reduz os níveis séricos de ciclosporina; monitorar níveis)",
      "Metotrexato (pode elevar a hematotoxicidade do metotrexato)",
      "Ácido acetilsalicílico (pode atenuar o efeito antiplaquetário do AAS se tomado simultaneamente)",
    ],
    monitoring: [
      "Sinais vitais (PA) durante administração parenteral",
      "Hemograma em tratamentos prolongados (> 7 dias) ou se surgirem febre/odinofagia inexplicadas",
    ],
    sources: [
      { title: "Bula Padrão do Medicamento / Formulário Terapêutico Nacional", organization: "Anvisa" },
      { title: "European Medicines Agency (EMA) Metamizole Safety Review", organization: "EMA" },
    ],
    reviewStatus: "reviewed",
    notes: "Primeira escolha de analgésico/antipirético no cenário hospitalar e emergencial brasileiro por sua alta eficácia e segurança gástrica/renal relativa frente aos AINEs.",
  },
  {
    id: "paracetamol",
    genericName: "Paracetamol (Acetaminofeno)",
    brandNames: ["Tylenol", "Parador"],
    therapeuticClass: "Analgésico e Antipirético",
    mechanism: "Inibição central da síntese de prostaglandinas e ativação de vias serotoninérgicas inibitórias descendentes na medula espinhal, sem atividade anti-inflamatória periférica significativa.",
    presentations: [
      "Comprimidos de 500 mg e 750 mg",
      "Suspensão / Gotas pediátricas: 200 mg/mL (1 mL = ~15 a 20 gotas)",
      "Solução oral: 100 mg/mL",
    ],
    doseProfiles: [
      {
        population: "Adultos e Adolescentes (> 12 anos)",
        indication: "Dor Leve a Moderada e Febre",
        route: "Via Oral",
        presentation: "Comprimidos 500 mg e 750 mg",
        initial: "500 mg a 1000 mg por tomada",
        titration: "Repetir a cada 4 a 6 horas conforme dor ou febre",
        usual: "500 mg a 750 mg a cada 6 horas",
        interval: "A cada 4 horas ou 6 horas (respeitar intervalo mínimo de 4h)",
        target: "Alívio álgico",
        maximum: "4000 mg/dia em adultos hígidos; limitar a 2000 mg a 3000 mg/dia em hepatopatas, idosos ou alcoolistas crônicos",
        duration: "Curto prazo",
        renalAdjustment: "Ampliar intervalo para cada 6h ou 8h se TFG < 30 mL/min.",
        hepaticAdjustment: "Contraindicado em hepatite aguda ou insuficiência hepática descompensada grave.",
        notes: "O esgotamento das reservas de glutationa hepática expõe os hepatócitos ao acúmulo citotóxico de NAPQI.",
      },
      {
        population: "Pediátrico",
        indication: "Antipirese e Analgesia Infantil",
        route: "Via Oral",
        presentation: "Gotas 200 mg/mL (1 gota = ~10 a 14 mg dependendo do bico dosador) ou Suspensão 100 mg/mL",
        initial: "10 mg a 15 mg/kg por tomada",
        titration: "A cada 4 a 6 horas se febre persistente",
        usual: "10 mg a 15 mg/kg/dose",
        interval: "A cada 4 a 6 horas (máximo 5 tomadas em 24h)",
        target: "Controle da temperatura",
        maximum: "75 mg/kg/dia",
        duration: "Curto prazo",
        renalAdjustment: "Sem restrição para doses agudas.",
        hepaticAdjustment: "Não exceder doses ponderais.",
        notes: "Intoxicação aguda reversível com N-acetilcisteína (NAC) precoce.",
      },
    ],
    contraindications: ["Hipersensibilidade grave, insuficiência hepática grave ou cirrose Child-Pugh C."],
    warnings: [
      "Hepatotoxicidade dose-dependente severa com risco de necrose centrolobular massiva",
      "Atenção para intoxicação cumulativa inadvertida por associação com antigripais compostos de venda livre",
    ],
    interactions: [
      "Álcool etílico (indução do CYP2E1 que amplia a conversão para o metabólito tóxico NAPQI)",
      "Varfarina (doses regulares > 2 g/dia por vários dias aumentam o INR)",
    ],
    monitoring: ["Transaminases e TAP/INR em suspeita de superdosagem; avaliação clínica de icterícia."],
    sources: [{ title: "FDA Drug Safety Communication: Acetaminophen", organization: "FDA" }],
    reviewStatus: "reviewed",
    notes: "Analgésico mais seguro durante todos os trimestres da gestação e na lactação.",
  },
  {
    id: "ibuprofeno",
    genericName: "Ibuprofeno",
    brandNames: ["Advil", "Alivium", "Motrin"],
    therapeuticClass: "Anti-inflamatório Não Esteroidal (AINE) / Derivado do Ácido Propiônico",
    mechanism: "Inibição não seletiva reversível das enzimas ciclo-oxigenase 1 e 2 (COX-1 e COX-2), bloqueando a síntese de prostanoides e prostaglandinas inflamatórias.",
    presentations: [
      "Comprimidos de 200 mg, 400 mg e 600 mg",
      "Gotas / Suspensão oral: 50 mg/mL e 100 mg/mL",
    ],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Dor Inflamatória, Cefaleia e Dismenorreia",
        route: "Via Oral",
        presentation: "Comprimidos 400 mg e 600 mg",
        initial: "200 mg a 400 mg a cada 4 a 6h (analgesia) ou 600 mg a cada 8h (anti-inflamatório)",
        titration: "Ajustar conforme intensidade dos sintomas",
        usual: "400 mg a cada 6 horas ou 600 mg a cada 8 horas",
        interval: "A cada 6 horas ou 8 horas",
        target: "Resolução dos sinais flogísticos e dor",
        maximum: "2400 mg/dia",
        duration: "Restringir ao menor tempo possível (idealmente < 5 a 7 dias)",
        renalAdjustment: "Evitar o uso se TFG < 30 mL/min/1,73m².",
        hepaticAdjustment: "Evitar em doença hepática terminal.",
        notes: "Administrar preferencialmente após as refeições para mitigar irritação gástrica direta.",
      },
      {
        population: "Pediátrico (> 6 meses)",
        indication: "Febre e Processos Inflamatórios Infantis",
        route: "Via Oral",
        presentation: "Gotas 50 mg/mL ou 100 mg/mL",
        initial: "5 mg a 10 mg/kg/dose",
        titration: "A cada 6 a 8 horas",
        usual: "5 mg a 10 mg/kg/dose",
        interval: "A cada 6 horas ou 8 horas",
        target: "Defervescência e conforto",
        maximum: "40 mg/kg/dia",
        duration: "3 a 5 dias",
        renalAdjustment: "Evitar se desidratação infantil aguda.",
        hepaticAdjustment: "Sem restrição direta em uso breve.",
        notes: "Não indicado em menores de 6 meses de vida.",
      },
    ],
    contraindications: [
      "Úlcera péptica ativa ou histórico de sangramento/perfuração gastrointestinal por AINEs",
      "Insuficiência cardíaca grave descompensada",
      "Disfunção renal severa (TFG < 30)",
      "Terceiro trimestre de gestação (fechamento prematuro do canal arterial)",
    ],
    warnings: [
      "Gastrolesividade: erosões, úlceras e sangramento digestivo alto por inibição de COX-1 gástrica protetora",
      "Injúria Renal Aguda hemodinâmica por bloqueio da síntese de PGE2 e PGI2 (vasoconstrição da arteríola aferente)",
      "Aumento do risco de eventos trombóticos cardiovasculares em doses altas (> 1200 mg a 2400 mg/dia)",
    ],
    interactions: [
      "AAS (ibuprofeno bloqueia o acesso do AAS ao sítio catalítico da COX-1 plaquetária se administrado antes)",
      "Anti-hipertensivos / IECAs e diuréticos (antagonismo do efeito hipotensor e risco crítico de nefrotoxicidade)",
      "Anticoagulantes orais (aumento pronunciado do risco hemorrágico digestivo)",
    ],
    monitoring: ["Hemoglobina/hematócrito, função renal e PA em tratamentos com mais de 7 dias."],
    sources: [{ title: "Goodman & Gilman", organization: "McGraw-Hill" }],
    reviewStatus: "reviewed",
    notes: "Menor potencial trombótico cardiovascular relativo entre os AINEs tradicionais quando restrito a doses < 1200 mg/dia.",
  },
  {
    id: "cetoprofeno",
    genericName: "Cetoprofeno",
    brandNames: ["Profenid", "Artril", "Profenid Entérico"],
    therapeuticClass: "Anti-inflamatório Não Esteroidal (AINE)",
    mechanism: "Inibição de COX-1 e COX-2 e estabilização de membranas lisossomais com inibição colateral de vias da lipoxigenase e migração leucocitária.",
    presentations: [
      "Cápsulas de 50 mg",
      "Comprimidos revestidos de 100 mg",
      "Comprimidos de liberação prolongada de 200 mg",
      "Ampolas injetáveis IV/IM de 100 mg/2 mL",
    ],
    doseProfiles: [
      {
        population: "Adultos",
        indication: "Dor Inflamatória Musculoesquelética Aguda, Crises de Gota e Pós-Operatório",
        route: "Via Oral / Via Intravenosa / Via Intramuscular",
        presentation: "Comprimidos 100 mg; Cápsulas 50 mg; Liberação Prolongada 200 mg; Ampolas 100 mg",
        initial: "100 mg a cada 12h ou 50 mg a cada 6-8h VO; 100 mg IV a cada 12h diluído em 100 mL de SF0,9%",
        titration: "Sem titulação; usar a menor dose eficaz",
        usual: "150 mg a 200 mg/dia",
        interval: "A cada 12 horas ou 24 horas (formulações de 200 mg LP)",
        target: "Remissão do processo álgico e inflamatório",
        maximum: "300 mg/dia",
        duration: "Restringir a no máximo 3 a 5 dias para uso injetável e 7 dias para via oral",
        renalAdjustment: "Contraindicado em insuficiência renal grave; reduzir dose em 50% em idosos ou DRC estágio 3.",
        hepaticAdjustment: "Reduzir dose em disfunção hepática.",
        notes: "Infusão intravenosa deve correr em período de 20 a 30 minutos.",
      },
    ],
    contraindications: [
      "Tríade da aspirina (asma, pólipos nasais e hipersensibilidade a AINEs)",
      "Hemorragia digestiva ativa",
      "Insuficiência cardíaca classe III/IV",
      "Pós-operatório imediato de cirurgia de revascularização miocárdica (CRM)",
      "Gestação após 20 semanas",
    ],
    warnings: [
      "Potente toxicidade sobre a mucosa gástrica e duodenal",
      "Retenção hidrossalina com descompensação de PA e IC",
      "Inibição plaquetária reversível",
    ],
    interactions: [
      "Metotrexato em altas doses (grave risco de toxicidade medular por redução de clearance)",
      "Lítio (elevação importante da concentração plasmática do lítio)",
      "Inibidores da recaptação de serotonina (ISRS) elevam o risco de sangramentos gastrointestinais",
    ],
    monitoring: ["Creatinina, ureia, hemograma, dor epigástrica e melena."],
    sources: [{ title: "Formulário Terapêutico Nacional", organization: "Ministério da Saúde" }],
    reviewStatus: "reviewed",
    notes: "AINE de expressiva potência anti-inflamatória e analgésica rápida, rotineiramente combinado a inibidores de bomba de prótons (IBP) como gastroproteção em pacientes de risco.",
  },
];