"use client";
import {useMemo,useState} from "react";
import {conditions,examKnowledge} from "@/src/clinical/content";
import {VaccinesPanel} from "./vaccines-panel";
import {pharmacologyCatalog} from "@/src/clinical/pharmacology/catalog";
import {publishablePharmacologyEntries} from "@/src/clinical/pharmacology/validation";
import {sourceById,clinicalSources} from "@/src/clinical/sources";
import {validateClinicalLibrary} from "@/src/clinical/validation";
import type {ClinicalCondition} from "@/src/clinical/types";

type View="conditions"|"medications"|"exams"|"vaccines"|"sources";
export function ClinicalLibrary(){const[view,setView]=useState<View>("conditions");const[query,setQuery]=useState("");const[selected,setSelected]=useState<ClinicalCondition>();const validation=useMemo(()=>validateClinicalLibrary(),[]);const q=query.toLowerCase();const filtered=conditions.filter((c)=>[c.name,c.shortName,...c.synonyms,c.summary].join(" ").toLowerCase().includes(q));return <section className="clinical-library"><header className="clinical-header"><div><p className="eyebrow">Biblioteca clínica</p><h1>Clínica</h1></div><span className={validation.valid?"clinical-status ok":"clinical-status error"}>{validation.valid?"Estrutura válida":"Revisar estrutura"}</span></header><label className="clinical-search"><span>Buscar</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Condição, exame ou medicamento"/></label><nav className="clinical-tabs">{(["conditions","medications","exams","vaccines","sources"] as View[]).map((item)=><button className={view===item?"active":""} onClick={()=>{setView(item);setSelected(undefined)}} key={item}>{item==="conditions"?"Condições":item==="medications"?"Medicamentos":item==="exams"?"Exames":item==="vaccines"?"Vacinas":"Fontes"}</button>)}</nav>
{view==="conditions"&&!selected&&<div className="clinical-grid">{filtered.map((condition)=><button className="clinical-card" onClick={()=>setSelected(condition)} key={condition.id}><span>{condition.publicationLevel}</span><h2>{condition.shortName}</h2><p>{condition.summary}</p><small>{condition.sourceIds.length} fonte(s)</small></button>)}</div>}
{view==="conditions"&&selected&&<ConditionDetail condition={selected} onBack={()=>setSelected(undefined)}/>} 
{view==="medications"&&<div className="clinical-grid">{publishablePharmacologyEntries(pharmacologyCatalog).filter((m)=>[m.genericName,m.therapeuticClass,...(m.brandNames??[])].join(" ").toLowerCase().includes(q)).map((m)=><article className="clinical-card static" key={m.id}><span>{m.reviewStatus}</span><h2>{m.genericName}</h2><strong>{m.therapeuticClass}</strong>{m.mechanism&&<p>{m.mechanism}</p>}<h3>Apresentações</h3><ul>{m.presentations.map((x)=><li key={x}>{x}</li>)}</ul>{m.doseProfiles.map((d,i)=><section className="claim" key={`${m.id}-${i}`}><h3>{d.indication} · {d.population}</h3><p><b>Via:</b> {d.route} · <b>Apresentação:</b> {d.presentation}</p>{d.initial&&<p><b>Início:</b> {d.initial}</p>}{d.titration&&<p><b>Titulação:</b> {d.titration}</p>}{d.usual&&<p><b>Usual:</b> {d.usual}</p>}{d.interval&&<p><b>Intervalo:</b> {d.interval}</p>}{d.target&&<p><b>Alvo:</b> {d.target}</p>}{d.maximum&&<p><b>Máxima:</b> {d.maximum}</p>}{d.renalAdjustment&&<p><b>Ajuste renal:</b> {d.renalAdjustment}</p>}{d.hepaticAdjustment&&<p><b>Ajuste hepático:</b> {d.hepaticAdjustment}</p>}{d.notes&&<p>{d.notes}</p>}</section>)}<h3>Monitoramento</h3><ul>{m.monitoring.map((x)=><li key={x}>{x}</li>)}</ul><div className="source-links">{m.sources.map((source,i)=>source.url?<a key={`${m.id}-source-${i}`} href={source.url} target="_blank" rel="noreferrer">{source.organization}: {source.title}</a>:<span key={`${m.id}-source-${i}`}>{source.organization}: {source.title}</span>)}</div></article>)}{publishablePharmacologyEntries(pharmacologyCatalog).length===0&&<article className="clinical-card static"><span>Caderno autoral</span><h2>Catálogo farmacológico vazio</h2><p>Adicione tuas fichas em <code>src/clinical/pharmacology/catalog.ts</code>.</p><small>Use o molde em <code>src/clinical/pharmacology/example.ts</code>.</small></article>}</div>}
{view==="exams"&&<div className="clinical-grid">{examKnowledge.filter((e)=>[e.name,e.purpose].join(" ").toLowerCase().includes(q)).map((e)=><article className="clinical-card static" key={e.id}><span>{e.publicationLevel}</span><h2>{e.name}</h2><p>{e.purpose}</p><h3>Travas interpretativas</h3><ul>{e.interpretationGuardrails.map((x)=><li key={x}>{x}</li>)}</ul><SourceLinks ids={e.sourceIds}/></article>)}</div>}
{view==="vaccines"&&<VaccinesPanel/>}{view==="sources"&&<div className="source-list">{clinicalSources.map((source)=><article key={source.id}><div><span>{source.kind} · {source.status}</span><h2>{source.title}</h2><p>{source.organization} · {source.publishedAt}{source.updatedAt?` · atualizado ${source.updatedAt}`:""}</p>{source.notes&&<p className="safety-callout">{source.notes}</p>}</div><a href={source.url} target="_blank" rel="noreferrer">Abrir fonte</a></article>)}</div>}
<footer className="clinical-footer"><strong>Caderno farmacológico:</strong> a interface mostra as fichas do catálogo que passam pela validação; o molde de exemplo não é carregado no aplicativo.</footer></section>}
function ConditionDetail({condition,onBack}:{condition:ClinicalCondition;onBack:()=>void}){return <article className="condition-detail"><button className="back-button" onClick={onBack}>← Voltar</button><span className="clinical-status">{condition.publicationLevel}</span><h1>{condition.name}</h1><p>{condition.summary}</p><p className="shared-callout">Para a pessoa: {condition.sharedSummary}</p><p className="scope-callout">Escopo: {condition.scope}</p>{Object.entries(condition.sections).map(([key,claims])=><section key={key}><h2>{sectionLabel(key)}</h2>{claims.map((claim)=><article className="claim" key={claim.id}><p>{claim.text}</p>{claim.sharedText&&<p className="shared-callout">{claim.sharedText}</p>}<div><span>{claim.level}</span><span>revisado {claim.reviewedAt}</span><span>revisar até {claim.reviewDueAt}</span></div><SourceLinks ids={claim.sourceIds}/></article>)}</section>)}<SourceLinks ids={condition.sourceIds}/></article>}
function SourceLinks({ids}:{ids:string[]}){return <div className="source-links">{ids.map((id)=>{const s=sourceById(id);return s?<a key={id} href={s.url} target="_blank" rel="noreferrer">{s.organization}: {s.title}</a>:<span key={id}>Fonte ausente: {id}</span>})}</div>}
function sectionLabel(key:string){return ({quick:"Visão rápida",diagnosis:"Diagnóstico",assessment:"Avaliação inicial",monitoring:"Monitoramento",nonDrug:"Manejo não farmacológico",medication:"Farmacologia",referral:"Encaminhamento"} as Record<string,string>)[key]??key}
