"use client";
import {type FormEvent,type RefObject,useEffect,useMemo,useRef,useState} from "react";
import type {Family,FamilyMembership,Person} from "@/src/contracts/family";
import type {ExternalLink,ExternalResource,InterpersonalRelationship,RelationshipQuality} from "@/src/contracts/relations";
import {toSvg} from "html-to-image";
import {buildEcomap,buildGenogram,relationshipNarrative,type DiagramModel} from "@/src/domain/diagram-engine";
import {FamilyDiagramFlow} from "./family-relations-flow";
import {translateFlowError} from "@/src/domain/diagram-labels";
import {diagramPrompt,possibleIdentifiers} from "@/src/domain/diagram-prompt";
import {createExternalLink,createRelationship,createResource} from "@/src/domain/relation-factories";
import {ENTITY_TYPES} from "@/src/domain/entity-types";import {saveEntity} from "@/src/domain/repository";
import {getApplication,type EcomapLink,type EcomapLinkProposal} from "@/src/clinical/assessments";
import {decideProposal,ecomapLinkFromProposal,listEcomapLinksForFamily,listProposalsForFamily,persistEcomapLink,persistProposal} from "@/src/clinical/assessments/proposals";
interface Props{family:Family;people:Person[];memberships:FamilyMembership[];relationships:InterpersonalRelationship[];resources:ExternalResource[];links:ExternalLink[];onSaved:()=>Promise<void>;onSelectPerson?:(personId:string)=>void}
type View="genogram"|"ecomap"|"narrative"|"prompt";type Composer="relationship"|"resource"|"external-link"|null;
export function FamilyRelations(p:Props){
  const[selectedNode,setSelectedNode]=useState("");const[view,setView]=useState<View>("genogram");const[layer,setLayer]=useState<"structural"|"household"|"clinical"|"functional">("structural");const[perspective,setPerspective]=useState("");const[composer,setComposer]=useState<Composer>(null);const[message,setMessage]=useState("");const flowRef=useRef<HTMLDivElement>(null);const model=useMemo(()=>view==="ecomap"?buildEcomap({family:p.family,people:p.people,resources:p.resources,links:p.links,...(perspective?{perspectivePersonId:perspective}:{})}):buildGenogram({family:p.family,people:p.people,memberships:p.memberships,relationships:p.relationships,layer,...(perspective?{perspectivePersonId:perspective}:{})}),[view,layer,perspective,p]);const prompt=diagramPrompt(model);const ids=possibleIdentifiers(prompt);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(composer==="relationship")await saveEntity(ENTITY_TYPES.interpersonalRelationship,createRelationship({familyId:p.family.id,sourcePersonId:String(f.get("source")),targetPersonId:String(f.get("target")),formalType:String(f.get("formalType")),quality:String(f.get("quality")) as RelationshipQuality,perspectiveLabel:String(f.get("perspectiveLabel")),...(String(f.get("perspectivePersonId"))?{perspectivePersonId:String(f.get("perspectivePersonId"))}:{}),thirdParty:f.get("thirdParty")==="on"}));if(composer==="resource"){const resource=createResource({familyId:p.family.id,name:String(f.get("name")),type:String(f.get("type")) as ExternalResource["type"],state:String(f.get("state")) as ExternalResource["state"]});await saveEntity(ENTITY_TYPES.externalResource,resource)}if(composer==="external-link")await saveEntity(ENTITY_TYPES.externalLink,createExternalLink({familyId:p.family.id,resourceId:String(f.get("resourceId")),...(String(f.get("personId"))?{personId:String(f.get("personId"))}:{}),quality:String(f.get("quality")) as RelationshipQuality,perspectiveLabel:String(f.get("perspectiveLabel")),...(String(f.get("perspectivePersonId"))?{perspectivePersonId:String(f.get("perspectivePersonId"))}:{}),thirdParty:f.get("thirdParty")==="on"}));await p.onSaved();setComposer(null);setMessage("Relação salva com perspectiva e temporalidade.")}
async function exportSvg(){const viewport=flowRef.current?.querySelector<HTMLElement>(".react-flow__viewport");const surface=flowRef.current;if(!viewport||!surface){setMessage("Nada para exportar nesta visao.");return}try{const styles=getComputedStyle(surface);const backgroundColor=styles.backgroundColor.includes("rgba(0, 0, 0, 0)")||styles.backgroundColor==="transparent"?getComputedStyle(document.body).backgroundColor:styles.backgroundColor;const dataUrl=await toSvg(viewport,{backgroundColor,width:viewport.offsetWidth,height:viewport.offsetHeight,cacheBust:true,style:{width:`${viewport.offsetWidth}px`,height:`${viewport.offsetHeight}px`}});const a=document.createElement("a");a.href=dataUrl;a.download=`mapa-${view}-${p.family.code}.svg`;a.click();setMessage("Diagrama SVG exportado no tamanho exibido.");}catch{setMessage("Nao foi possivel exportar o diagrama neste dispositivo.")}}
return <section className="relations-panel"><div className="relations-head"><div><p className="eyebrow">Relações</p><h2>Família, vínculos e território</h2></div><button onClick={()=>setComposer(view==="ecomap"?"resource":"relationship")}>Adicionar</button></div><p role="status" className="system-message">{message}</p><ProposalReview familyId={p.family.id} onChanged={p.onSaved}/><div className="relations-tabs">{(["genogram","ecomap","narrative","prompt"] as View[]).map(x=><button className={view===x?"active":""} onClick={()=>setView(x)} key={x}>{x==="genogram"?"Genograma":x==="ecomap"?"Ecomapa":x==="narrative"?"Narrativa":"Prompt IA"}</button>)}</div><div className="diagram-controls"><label>Perspectiva<select value={perspective} onChange={e=>setPerspective(e.target.value)}><option value="">Consolidada</option>{p.people.map(x=><option key={x.id} value={x.id}>{x.displayName||x.code}</option>)}</select></label>{view==="genogram"&&<label>Camada<select value={layer} onChange={e=>setLayer(e.target.value as typeof layer)}><option value="structural">Estrutural</option><option value="household">Domiciliar</option><option value="clinical">Clínica</option><option value="functional">Funcional</option></select></label>}<button onClick={exportSvg} disabled={view==="narrative"||view==="prompt"}>Exportar SVG</button>{view==="ecomap"&&<button onClick={()=>setComposer("external-link")} disabled={!p.resources.length}>Vincular recurso</button>}</div>{(view==="genogram"||view==="ecomap")&&<FamilyDiagramFlow model={model} containerRef={flowRef} showLegend selectedNodeId={selectedNode} onSelectNode={(id)=>{setSelectedNode(id);if(p.people.some((person)=>person.id===id))p.onSelectPerson?.(id);}} onFlowError={(code,message)=>{console.warn(`[diagrama] ${code}: ${message}`);setMessage(translateFlowError(code,message));}}/>} {view==="narrative"&&<pre className="diagram-text">{relationshipNarrative(model)}</pre>} {view==="prompt"&&<section className="prompt-panel"><p className={ids.length?"safety-callout":"shared-callout"}>{ids.length?`Possíveis identificadores encontrados: ${ids.length}. Revise antes de copiar.`:"Nenhum identificador direto óbvio detectado. A revisão manual continua obrigatória."}</p><textarea readOnly value={prompt}/><button onClick={async()=>{await navigator.clipboard.writeText(prompt);setMessage("Prompt copiado para a área de transferência.")}}>Copiar prompt estruturado</button></section>}{composer&&<div className="sheet-backdrop"><section className="sheet"><button className="close-button" onClick={()=>setComposer(null)}>×</button><RelationForm kind={composer} people={p.people} resources={p.resources} onSubmit={submit}/></section></div>}<DiagramDescription model={model}/></section>}
function ProposalReview({familyId,onChanged}:{familyId:string;onChanged:()=>Promise<void>}){
  const[proposals,setProposals]=useState<EcomapLinkProposal[]>([]);
  const[links,setLinks]=useState<EcomapLink[]>([]);
  const[drafts,setDrafts]=useState<Record<string,string>>({});
  const[message,setMessage]=useState("");
  useEffect(()=>{void Promise.all([listProposalsForFamily(familyId),listEcomapLinksForFamily(familyId)]).then(([nextProposals,nextLinks])=>{setProposals(nextProposals);setLinks(nextLinks);}).catch((error:unknown)=>setMessage(error instanceof Error?error.message:"Não foi possível ler as propostas."));},[familyId]);
  async function reload(){setProposals(await listProposalsForFamily(familyId));setLinks(await listEcomapLinksForFamily(familyId));}
  async function decide(proposal:EcomapLinkProposal,decision:"confirmed"|"rejected"){
    try{
      const shareableText=drafts[proposal.proposalId]??"";
      const decided=decideProposal(proposal,decision,shareableText.trim()?{shareableText}:{});
      await persistProposal(decided);
      const application=await getApplication(proposal.applicationId);
      if(application){const link=ecomapLinkFromProposal(decided,application);if(link)await persistEcomapLink(link);}
      await reload();await onChanged();
      setMessage(decision==="confirmed"?"Proposta confirmada e registrada no ecomapa com a origem da aplicação.":"Proposta rejeitada e mantida no histórico.");
    }catch(error){setMessage(error instanceof Error?error.message:"Não foi possível registrar a decisão.");}
  }
  const pending=proposals.filter((item)=>item.decision==="pending-review");
  return <section className="card proposal-review" aria-labelledby={`proposals-${familyId}`}>
    <div className="section-head"><div><p className="eyebrow">Revisão humana</p><h3 id={`proposals-${familyId}`}>Mudanças propostas pela ficha</h3></div></div>
    <p className="fine-print">Serviços marcados na avaliação são propostas. Nenhum vínculo do ecomapa nasce sem confirmação e texto compartilhável.</p>
    {pending.length?pending.map((proposal)=><article className="proposal-card" key={proposal.proposalId}>
      <div><strong>{proposal.serviceOrNetworkId.replace(/-/g," ")}</strong><span>Pessoa {proposal.subjectPersonId} · {proposal.proposedScope==="family"?"família inteira":"integrantes selecionados"}</span><small>{proposal.justificationPrivate}</small></div>
      <label>Texto para a pessoa<input value={drafts[proposal.proposalId]??""} onChange={(event)=>setDrafts((current)=>({...current,[proposal.proposalId]:event.target.value}))} placeholder="Ex.: encaminhamento à UBS, a combinar com a pessoa." /></label>
      <div className="action-row"><button onClick={()=>void decide(proposal,"confirmed")}>Confirmar e registrar no ecomapa</button><button className="secondary" onClick={()=>void decide(proposal,"rejected")}>Rejeitar</button></div>
    </article>):<p className="fine-print">Nenhuma proposta aguardando revisão.</p>}
    {links.length?<><h4>Vínculos originados por avaliação</h4><ul className="proposal-links">{links.map((link)=><li key={link.networkRelationshipId}>{link.serviceOrNetworkId.replace(/-/g," ")} · {link.status} · origem {link.originApplicationId??"manual"}</li>)}</ul></>:null}
    <p className="system-message" role="status" aria-live="polite">{message}</p>
  </section>;
}

function DiagramDescription({model}:{model:DiagramModel}){return <details className="diagram-description"><summary>Descrição textual acessível</summary><pre>{relationshipNarrative(model)}</pre></details>}
function RelationForm({kind,people,resources,onSubmit}:{kind:NonNullable<Composer>;people:Person[];resources:ExternalResource[];onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="form-stack" onSubmit={onSubmit}><p className="eyebrow">Abordagem familiar</p><h2>{kind==="relationship"?"Nova relação":kind==="resource"?"Novo recurso":"Vincular recurso"}</h2>{kind==="relationship"&&<><label>Origem<select name="source" required>{people.map(p=><option key={p.id} value={p.id}>{p.displayName||p.code}</option>)}</select></label><label>Destino<select name="target" required>{people.map(p=><option key={p.id} value={p.id}>{p.displayName||p.code}</option>)}</select></label><label>Relação formal<input name="formalType" placeholder="Ex.: mãe, companheira, cuidado" required/></label></>}{kind==="resource"&&<><label>Nome<input name="name" required/></label><label>Tipo<select name="type"><option value="health">Saúde</option><option value="education">Educação</option><option value="community">Comunidade</option><option value="extended-family">Família ampliada</option><option value="social-assistance">Assistência social</option><option value="work">Trabalho</option><option value="other">Outro</option></select></label><label>Estado<select name="state"><option value="active">Ativo</option><option value="potential">Potencial</option><option value="inactive">Inativo</option></select></label></>}{kind==="external-link"&&<><label>Recurso<select name="resourceId">{resources.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Pessoa específica (opcional)<select name="personId"><option value="">Família inteira</option>{people.map(p=><option key={p.id} value={p.id}>{p.displayName||p.code}</option>)}</select></label></>}{kind!=="resource"&&<><label>Qualidade<select name="quality"><option value="adequate">Adequado</option><option value="strong">Forte</option><option value="weak">Fraco</option><option value="conflict">Conflitivo</option><option value="ruptured">Rompido</option><option value="divergent">Divergente</option><option value="unknown">Desconhecido</option></select></label><label>Perspectiva<select name="perspectivePersonId"><option value="">Consolidada</option>{people.map(p=><option key={p.id} value={p.id}>{p.displayName||p.code}</option>)}</select></label><label>Descrição da perspectiva<input name="perspectiveLabel" defaultValue="Relato atual" required/></label><label className="check-row"><input type="checkbox" name="thirdParty"/>Informação confidencial de terceiro</label></>}<button type="submit">Salvar</button></form>}
