"use client";
import { type FormEvent, type ReactNode, useMemo, useState } from "react";
import type { Person } from "@/src/contracts/family";
import type { CarePlan, ConditionRecord, ExamResultRecord, PersonMedicationRecord, ScreeningEpisode } from "@/src/contracts/longitudinal";
import type { Encounter } from "@/src/contracts/care";
import { createCarePlan, createCondition, createExamResult, createMedication, createPatientSuggestion, createScreening } from "@/src/domain/longitudinal-factories";
import { buildHandoff, createSharedCards, transcriptionText } from "@/src/domain/care-selectors";
import { ENTITY_TYPES } from "@/src/domain/entity-types";
import { saveEntity } from "@/src/domain/repository";
import { verifyPin } from "@/src/security/pin";

interface Props { person:Person; familyId:string; conditions:ConditionRecord[]; medications:PersonMedicationRecord[]; exams:ExamResultRecord[]; screenings:ScreeningEpisode[]; plans:CarePlan[]; encounters:Encounter[]; onSaved:()=>Promise<void>; }
type Composer="condition"|"medication"|"exam"|"screening"|"plan"|null;
export function PersonCarePanel(props:Props){
 const [composer,setComposer]=useState<Composer>(null); const [presentation,setPresentation]=useState(false); const [handoff,setHandoff]=useState<"30s"|"2min"|"full"|null>(null); const [transcription,setTranscription]=useState(false); const [selected,setSelected]=useState<Set<string>>(new Set());
 const entities=useMemo(()=>[...props.conditions,...props.medications,...props.exams,...props.screenings,...props.plans],[props.conditions,props.medications,props.exams,props.screenings,props.plans]);
 const cards=useMemo(()=>createSharedCards(entities),[entities]);
 const selectedCards=cards.filter((card)=>selected.has(card.id)&&!card.blocked);
 async function save(entityType:Parameters<typeof saveEntity>[0], entity:Parameters<typeof saveEntity>[1]){ await saveEntity(entityType,entity); await props.onSaved(); setComposer(null); }
 async function submit(event:FormEvent<HTMLFormElement>){ event.preventDefault(); const f=new FormData(event.currentTarget); if(composer==="condition") await save(ENTITY_TYPES.condition,createCondition({personId:props.person.id,label:String(f.get("label")),kind:String(f.get("kind")) as ConditionRecord["kind"],sharedSummary:String(f.get("sharedSummary")||""),thirdParty:f.get("thirdParty")==="on"})); if(composer==="medication") await save(ENTITY_TYPES.medication,createMedication({personId:props.person.id,reportedName:String(f.get("reportedName")),presentationText:String(f.get("presentationText")||""),prescribedUseText:String(f.get("prescribedUseText")||""),actualUseText:String(f.get("actualUseText")||""),sharedSummary:String(f.get("sharedSummary")||"")})); if(composer==="exam") await save(ENTITY_TYPES.examResult,createExamResult({personId:props.person.id,examName:String(f.get("examName")),valueText:String(f.get("valueText")),unit:String(f.get("unit")||""),...(String(f.get("collectedAt")||"") ? { collectedAt:String(f.get("collectedAt")) } : {}),documentAvailable:f.get("documentAvailable")==="on",sharedSummary:String(f.get("sharedSummary")||"")})); if(composer==="screening") await save(ENTITY_TYPES.screening,createScreening({personId:props.person.id,title:String(f.get("title")),sharedSummary:String(f.get("sharedSummary")||"")})); if(composer==="plan") await save(ENTITY_TYPES.carePlan,createCarePlan({personId:props.person.id,familyId:props.familyId,title:String(f.get("title")),objective:String(f.get("objective")),target:String(f.get("target")) as CarePlan["target"],sharedSummary:String(f.get("sharedSummary")||"")})); }
 const toggle=(id:string)=>setSelected((old)=>{const next=new Set(old); next.has(id)?next.delete(id):next.add(id); return next;});
 return <section className="care-panel">
  <div className="care-title"><div><p className="eyebrow">Mapa da pessoa</p><h2>{props.person.displayName||props.person.code}</h2></div><button onClick={()=>setPresentation(true)} disabled={!selectedCards.length}>Mostrar resumo</button></div>
  <div className="care-actions"><button onClick={()=>setComposer("condition")}>Condição</button><button onClick={()=>setComposer("medication")}>Medicamento</button><button onClick={()=>setComposer("exam")}>Exame</button><button onClick={()=>setComposer("screening")}>Rastreamento</button><button onClick={()=>setComposer("plan")}>Plano</button></div>
  <div className="care-sections"><CareSection title="Condições" count={props.conditions.length}>{props.conditions.map((item)=><CareRow key={item.id} title={item.originalLabel} meta={`${item.kind} · ${item.clinicalState}`} checked={selected.has(item.id)} blocked={Boolean(cards.find((c)=>c.id===item.id)?.blocked)} onToggle={()=>toggle(item.id)} />)}</CareSection><CareSection title="Medicamentos" count={props.medications.length}>{props.medications.map((item)=><CareRow key={item.id} title={item.reportedName} meta={`${item.state}${item.actualUseText?` · ${item.actualUseText}`:""}`} checked={selected.has(item.id)} blocked={Boolean(cards.find((c)=>c.id===item.id)?.blocked)} onToggle={()=>toggle(item.id)} />)}</CareSection><CareSection title="Exames" count={props.exams.length}>{props.exams.map((item)=><CareRow key={item.id} title={item.examName} meta={`${item.valueText}${item.unit?` ${item.unit}`:" · unidade ausente"}`} checked={selected.has(item.id)} blocked={Boolean(cards.find((c)=>c.id===item.id)?.blocked)} onToggle={()=>toggle(item.id)} />)}</CareSection><CareSection title="Rastreamentos" count={props.screenings.length}>{props.screenings.map((item)=><CareRow key={item.id} title={item.title} meta={item.state} checked={selected.has(item.id)} blocked={Boolean(cards.find((c)=>c.id===item.id)?.blocked)} onToggle={()=>toggle(item.id)} />)}</CareSection><CareSection title="Plano" count={props.plans.length}>{props.plans.map((item)=><CareRow key={item.id} title={item.title} meta={`${item.target} · ${item.state}`} checked={selected.has(item.id)} blocked={Boolean(cards.find((c)=>c.id===item.id)?.blocked)} onToggle={()=>toggle(item.id)} />)}</CareSection></div>
  <div className="professional-tools"><button onClick={()=>setHandoff("30s")}>Passagem 30 s</button><button onClick={()=>setHandoff("2min")}>Passagem 2 min</button><button onClick={()=>setHandoff("full")}>Passagem completa</button><button onClick={()=>setTranscription(true)}>Transcrição</button></div>
  {composer&&<div className="sheet-backdrop"><section className="sheet" role="dialog" aria-modal="true"><button className="close-button" onClick={()=>setComposer(null)}>×</button><CareForm kind={composer} onSubmit={submit}/></section></div>}
  {presentation&&<PresentationMode person={props.person} cards={selectedCards} onExit={()=>setPresentation(false)} onSuggest={async(text)=>{await saveEntity(ENTITY_TYPES.patientSuggestion,createPatientSuggestion({personId:props.person.id,text}));await props.onSaved();}}/>}
  {handoff&&<TextOverlay title={`Passagem ${handoff}`} text={formatHandoff(buildHandoff(props.person,entities,props.encounters,handoff))} onExit={()=>setHandoff(null)}/>} {transcription&&<TextOverlay title="Visão para transcrição" text={transcriptionText(props.person,entities,props.encounters)} onExit={()=>setTranscription(false)}/>} 
 </section>;
}
function CareSection({title,count,children}:{title:string;count:number;children:ReactNode}){const[open,setOpen]=useState(true);return <section className="care-section"><button className="care-section-head" onClick={()=>setOpen(!open)}><span>{title}</span><span>{count} {open?"⌃":"⌄"}</span></button>{open&&<div>{count?children:<p className="fine-print">Nenhum item registrado.</p>}</div>}</section>}
function CareRow({title,meta,checked,blocked,onToggle}:{title:string;meta:string;checked:boolean;blocked?:boolean;onToggle:()=>void}){return <article className="care-row"><div><strong>{title}</strong><small>{meta}</small></div><label><input type="checkbox" checked={checked} disabled={blocked} onChange={onToggle}/>{blocked?"Privado":"Resumo"}</label></article>}
function CareForm({kind,onSubmit}:{kind:NonNullable<Composer>;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form className="form-stack" onSubmit={onSubmit}><p className="eyebrow">Cuidado longitudinal</p><h2>Novo {kind}</h2>{kind==="condition"&&<><label>Termo registrado<input name="label" required/></label><label>Natureza<select name="kind"><option value="reported">Relatada</option><option value="confirmed">Confirmada</option><option value="hypothesis">Hipótese</option><option value="risk-factor">Fator de risco</option><option value="symptom">Sintoma</option><option value="vulnerability">Vulnerabilidade</option></select></label><label className="check-row"><input type="checkbox" name="thirdParty"/>Informação fornecida por terceiro</label></>}{kind==="medication"&&<><label>Nome informado<input name="reportedName" required/></label><label>Apresentação<input name="presentationText"/></label><label>Uso prescrito<input name="prescribedUseText"/></label><label>Uso real informado<input name="actualUseText"/></label></>}{kind==="exam"&&<><label>Exame<input name="examName" required/></label><label>Valor<input name="valueText" required/></label><label>Unidade<input name="unit"/></label><label>Data da coleta<input name="collectedAt" type="date"/></label><label className="check-row"><input type="checkbox" name="documentAvailable"/>Documento apresentado</label></>}{kind==="screening"&&<label>Rastreamento<input name="title" required/></label>}{kind==="plan"&&<><label>Título<input name="title" required/></label><label>Objetivo<textarea name="objective" required/></label><label>Alvo<select name="target"><option value="person">Pessoa</option><option value="caregiver">Cuidador</option><option value="dyad">Díade</option><option value="family">Família</option><option value="team">Equipe</option></select></label></>}<label>Linguagem para a pessoa<textarea name="sharedSummary" placeholder="Opcional. Escreva de forma clara, sem diagnóstico não confirmado."/></label><button type="submit">Salvar</button></form>}
function PresentationMode({person,cards,onExit,onSuggest}:{person:Person;cards:ReturnType<typeof createSharedCards>;onExit:()=>void;onSuggest:(text:string)=>Promise<void>}){const[suggestion,setSuggestion]=useState("");const[exitRequested,setExitRequested]=useState(false);const[exitPin,setExitPin]=useState("");const[exitMessage,setExitMessage]=useState("");async function confirmExit(){if(await verifyPin(exitPin)){onExit();return;}setExitMessage("PIN incorreto. O resumo continua isolado.");}return <div className="presentation-mode"><header><div><p>Resumo de acompanhamento</p><h1>{person.displayName||person.code}</h1></div><button onClick={()=>setExitRequested(true)}>Sair</button></header><main><p className="presentation-notice">Este material ajuda você a acompanhar seu cuidado. O prontuário completo permanece na unidade de saúde.</p>{cards.map((card)=><article key={card.id}><span>{card.sourceType}</span><h2>{card.title}</h2><p>{card.body}</p><small>{card.stateLabel}</small></article>)}<section className="suggestion-box"><h2>Algo precisa ser corrigido?</h2><textarea value={suggestion} onChange={(e)=>setSuggestion(e.target.value)} placeholder="Sua observação ficará pendente de revisão."/><button disabled={!suggestion.trim()} onClick={async()=>{await onSuggest(suggestion);setSuggestion("");}}>Enviar sugestão</button></section></main>{exitRequested&&<div className="presentation-exit"><section><h2>Voltar ao modo profissional</h2><p>Digite o PIN local para impedir acesso acidental às outras famílias.</p><input inputMode="numeric" pattern="[0-9]*" value={exitPin} onChange={(e)=>setExitPin(e.target.value)} aria-label="PIN local"/><button onClick={confirmExit}>Confirmar saída</button><button className="secondary" onClick={()=>{setExitRequested(false);setExitPin("");setExitMessage("");}}>Continuar no resumo</button><p role="status">{exitMessage}</p></section></div>}</div>}
function TextOverlay({title,text,onExit}:{title:string;text:string;onExit:()=>void}){return <div className="text-overlay"><header><h1>{title}</h1><button onClick={onExit}>Fechar</button></header><pre>{text}</pre></div>}
function formatHandoff(d:ReturnType<typeof buildHandoff>){return [`IDENTIFICAÇÃO`,d.identification,"","FATOS",...d.facts.map((x)=>`- ${x}`),"","INTERPRETAÇÕES",...(d.interpretations.length?d.interpretations.map((x)=>`- ${x}`):["- Não preenchidas automaticamente."]),"","AÇÕES",...(d.actions.length?d.actions.map((x)=>`- ${x}`):["- Nenhuma ação registrada."]),"","PERGUNTAS",...(d.questions.length?d.questions.map((x)=>`- ${x}`):["- Adicione suas perguntas antes da discussão."])].join("\n")}
