import type { ClinicalSource } from "./types";
export const clinicalSources:ClinicalSource[]=[
 {id:"ms-pcdt-has-2025",title:"PCDT da Hipertensão Arterial Sistêmica",organization:"Ministério da Saúde / Conitec",kind:"pcdt",publishedAt:"2025-07-23",url:"https://www.gov.br/conitec/pt-br/midias/protocolos/2026/pcdt-resumido/pcdt-resumido-da-hipertensao-arterial-sistemica/@@display-file/file",status:"current"},
 {id:"ms-pcdt-dm2-2026",title:"PCDT do Diabete Melito Tipo 2",organization:"Ministério da Saúde / Conitec",kind:"pcdt",publishedAt:"2026-02-21",updatedAt:"2026-06-23",url:"https://www.gov.br/conitec/pt-br/midias/protocolos/2026/pcdt-diabete-melito-tipo-2/@@display-file/file",status:"current"},
 {id:"ms-pcdt-drc-2024",title:"PCDT de Estratégias para Atenuar a Progressão da Doença Renal Crônica",organization:"Ministério da Saúde / Conitec",kind:"pcdt",publishedAt:"2024-09-16",updatedAt:"2025-02-10",url:"https://www.gov.br/conitec/pt-br/midias/protocolos/pcdt-de-estrategias-para-atenuar-a-progressao-da-doenca-renal-cronica",status:"current"},
 {id:"ms-pcdt-dislipidemia-2019",title:"PCDT da Dislipidemia: prevenção de eventos cardiovasculares e pancreatite",organization:"Ministério da Saúde / Conitec",kind:"pcdt",publishedAt:"2019-07-30",url:"https://www.gov.br/conitec/pt-br/midias/protocolos/pcdt_dislipidemia.pdf/@@display-file/file",status:"current",notes:"Existe consulta pública preliminar de atualização em setembro de 2026; não foi tratada como norma vigente."},
 {id:"ms-dislipidemia-cp94-2026",title:"Relatório preliminar do PCDT da Dislipidemia e Prevenção - CP 94",organization:"Ministério da Saúde / Conitec",kind:"guideline",publishedAt:"2026-09-15",url:"https://www.gov.br/conitec/pt-br/midias/consultas/relatorios/2026/relatorio-preliminar-pcdt-da-dislipidemia-e-prevencao-cp-94.pdf",status:"preliminary"},
 {id:"ms-pcdt-obesidade-2024",title:"PCDT de Sobrepeso e Obesidade em Adultos",organization:"Ministério da Saúde / Conitec",kind:"pcdt",publishedAt:"2020-11-11",updatedAt:"2024-07-08",url:"https://www.gov.br/saude/pt-br/assuntos/pcdt/s/sobrepeso-e-obesidade-em-adultos/view",status:"current"},
 {id:"ms-linhas-cuidado-2026",title:"Plataforma Linhas de Cuidado",organization:"Ministério da Saúde",kind:"line-of-care",publishedAt:"2022-12-07",updatedAt:"2026-03-04",url:"https://www.gov.br/saude/pt-br/composicao/saps/ecv/linhas-de-cuidado/plataforma-linhas-de-cuidado",status:"current"},
 {id:"anvisa-bulario-2026",title:"Bulário Eletrônico",organization:"Anvisa",kind:"regulatory",publishedAt:"2020-10-05",updatedAt:"2026-05-17",url:"https://www.gov.br/anvisa/pt-br/sistemas/bulario-eletronico",status:"current"},
 {id:"ms-rename-2024",title:"Relação Nacional de Medicamentos Essenciais 2024",organization:"Ministério da Saúde",kind:"rename",publishedAt:"2024-01-01",updatedAt:"2025-04-12",url:"https://www.gov.br/saude/pt-br/composicao/sectics/rename",status:"current"},
 {id:"pm-canoas-estoque-aberto",title:"Estoque Aberto — medicamentos da rede municipal",organization:"Prefeitura Municipal de Canoas",kind:"official-reference",publishedAt:"2026-10-03",url:"https://www.canoas.rs.gov.br/servicos/estoqueaberto/",status:"current",notes:"Consulta pública de disponibilidade e quantidade por farmácia municipal. Retirada presencial exige cadastro e documento."},
 {id:"ms-calendario-nacional-vacinacao-2026",title:"Calendário Nacional de Vacinação 2026 (criança, adolescente e jovem, adulto e idoso)",organization:"Ministério da Saúde / Programa Nacional de Imunizações",kind:"official-reference",publishedAt:"2026-02-06",url:"https://www.gov.br/saude/pt-br/vacinacao/calendario",status:"current",notes:"Página oficial que reúne os calendários por faixa etária."},
 {id:"ufsc-calendario-vacinacao-crianca-ufsc",title:"Calendário Técnico de Vacinação da Criança (esquema com COVID-19 aos 6, 7 e 9 meses)",organization:"Universidade Federal de Santa Catarina — Medicina",kind:"official-reference",publishedAt:"2024-01-01",url:"https://medicina.paginas.ufsc.br/files/2024/01/Calend%C3%A1rio-T%C3%A9cnico-de-Vacina%C3%A7%C3%A3o-Crian%C3%A7a.pdf",status:"current",notes:"Confirma a 2ª dose de COVID-19 aos 7 meses: 4 semanas após a 1ª e 8 semanas após a 2ª até a 3ª, aos 9 meses."},
 {id:"ms-calendario-nacional-vacinacao-adolescentes",title:"Calendário Nacional de Vacinação — Adolescente e Jovem (10 a 24 anos)",organization:"Ministério da Saúde / Programa Nacional de Imunizações",kind:"official-reference",publishedAt:"2026-02-06",url:"https://www.gov.br/saude/pt-br/vacinacao/arquivos/calendario-nacional-de-vacinacao-adolescentes-jovens",status:"current"},
 {id:"ms-calendario-nacional-vacinacao-idoso",title:"Calendário Nacional de Vacinação — Idoso (a partir de 60 anos)",organization:"Ministério da Saúde / Programa Nacional de Imunizações",kind:"official-reference",publishedAt:"2026-02-06",url:"https://www.gov.br/saude/pt-br/vacinacao/arquivos/calendario-nacional-de-vacinacao-idoso",status:"current"},
]
export const sourceById=(id:string)=>clinicalSources.find((source)=>source.id===id);
